// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: profiling.proto

package pb_profiling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfilingSwitch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommunicationOperator string `protobuf:"bytes,1,opt,name=CommunicationOperator,proto3" json:"CommunicationOperator,omitempty"`
	Step                  string `protobuf:"bytes,2,opt,name=Step,proto3" json:"Step,omitempty"`
	SaveCheckpoint        string `protobuf:"bytes,3,opt,name=SaveCheckpoint,proto3" json:"SaveCheckpoint,omitempty"`
	FP                    string `protobuf:"bytes,4,opt,name=FP,proto3" json:"FP,omitempty"`
	DataLoader            string `protobuf:"bytes,5,opt,name=DataLoader,proto3" json:"DataLoader,omitempty"`
}

func (x *ProfilingSwitch) Reset() {
	*x = ProfilingSwitch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profiling_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfilingSwitch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilingSwitch) ProtoMessage() {}

func (x *ProfilingSwitch) ProtoReflect() protoreflect.Message {
	mi := &file_profiling_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilingSwitch.ProtoReflect.Descriptor instead.
func (*ProfilingSwitch) Descriptor() ([]byte, []int) {
	return file_profiling_proto_rawDescGZIP(), []int{0}
}

func (x *ProfilingSwitch) GetCommunicationOperator() string {
	if x != nil {
		return x.CommunicationOperator
	}
	return ""
}

func (x *ProfilingSwitch) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ProfilingSwitch) GetSaveCheckpoint() string {
	if x != nil {
		return x.SaveCheckpoint
	}
	return ""
}

func (x *ProfilingSwitch) GetFP() string {
	if x != nil {
		return x.FP
	}
	return ""
}

func (x *ProfilingSwitch) GetDataLoader() string {
	if x != nil {
		return x.DataLoader
	}
	return ""
}

type DataStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobNsName string `protobuf:"bytes,1,opt,name=jobNsName,proto3" json:"jobNsName,omitempty"`
}

func (x *DataStatusReq) Reset() {
	*x = DataStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profiling_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStatusReq) ProtoMessage() {}

func (x *DataStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_profiling_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStatusReq.ProtoReflect.Descriptor instead.
func (*DataStatusReq) Descriptor() ([]byte, []int) {
	return file_profiling_proto_rawDescGZIP(), []int{1}
}

func (x *DataStatusReq) GetJobNsName() string {
	if x != nil {
		return x.JobNsName
	}
	return ""
}

type DataStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message         string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ProfilingSwitch *ProfilingSwitch `protobuf:"bytes,2,opt,name=profilingSwitch,proto3" json:"profilingSwitch,omitempty"`
	Code            int32            `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *DataStatusRes) Reset() {
	*x = DataStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profiling_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataStatusRes) ProtoMessage() {}

func (x *DataStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_profiling_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataStatusRes.ProtoReflect.Descriptor instead.
func (*DataStatusRes) Descriptor() ([]byte, []int) {
	return file_profiling_proto_rawDescGZIP(), []int{2}
}

func (x *DataStatusRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DataStatusRes) GetProfilingSwitch() *ProfilingSwitch {
	if x != nil {
		return x.ProfilingSwitch
	}
	return nil
}

func (x *DataStatusRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DataTypeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobNsName       string           `protobuf:"bytes,1,opt,name=jobNsName,proto3" json:"jobNsName,omitempty"`
	ProfilingSwitch *ProfilingSwitch `protobuf:"bytes,2,opt,name=profilingSwitch,proto3" json:"profilingSwitch,omitempty"`
}

func (x *DataTypeReq) Reset() {
	*x = DataTypeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profiling_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataTypeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTypeReq) ProtoMessage() {}

func (x *DataTypeReq) ProtoReflect() protoreflect.Message {
	mi := &file_profiling_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTypeReq.ProtoReflect.Descriptor instead.
func (*DataTypeReq) Descriptor() ([]byte, []int) {
	return file_profiling_proto_rawDescGZIP(), []int{3}
}

func (x *DataTypeReq) GetJobNsName() string {
	if x != nil {
		return x.JobNsName
	}
	return ""
}

func (x *DataTypeReq) GetProfilingSwitch() *ProfilingSwitch {
	if x != nil {
		return x.ProfilingSwitch
	}
	return nil
}

type DataTypeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *DataTypeRes) Reset() {
	*x = DataTypeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profiling_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataTypeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTypeRes) ProtoMessage() {}

func (x *DataTypeRes) ProtoReflect() protoreflect.Message {
	mi := &file_profiling_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTypeRes.ProtoReflect.Descriptor instead.
func (*DataTypeRes) Descriptor() ([]byte, []int) {
	return file_profiling_proto_rawDescGZIP(), []int{4}
}

func (x *DataTypeRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DataTypeRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_profiling_proto protoreflect.FileDescriptor

var file_profiling_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x53,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x34, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x74, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12,
	0x26, 0x0a, 0x0e, 0x53, 0x61, 0x76, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x53, 0x61, 0x76, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x46, 0x50, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x46, 0x50, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x4c,
	0x6f, 0x61, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x61, 0x74,
	0x61, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x6f, 0x62, 0x4e,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x6f, 0x62,
	0x4e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x79, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3a, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x52, 0x0f, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x67, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x6f, 0x62, 0x4e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x6f, 0x62, 0x4e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3a,
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x69, 0x6e, 0x67, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x69, 0x6e, 0x67, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x22, 0x3b, 0x0a, 0x0b, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x8e, 0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x3b, 0x0a,
	0x1d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x63, 0x65, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x0c,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x0e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x70, 0x62,
	0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_profiling_proto_rawDescOnce sync.Once
	file_profiling_proto_rawDescData = file_profiling_proto_rawDesc
)

func file_profiling_proto_rawDescGZIP() []byte {
	file_profiling_proto_rawDescOnce.Do(func() {
		file_profiling_proto_rawDescData = protoimpl.X.CompressGZIP(file_profiling_proto_rawDescData)
	})
	return file_profiling_proto_rawDescData
}

var file_profiling_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_profiling_proto_goTypes = []interface{}{
	(*ProfilingSwitch)(nil), // 0: ProfilingSwitch
	(*DataStatusReq)(nil),   // 1: DataStatusReq
	(*DataStatusRes)(nil),   // 2: DataStatusRes
	(*DataTypeReq)(nil),     // 3: DataTypeReq
	(*DataTypeRes)(nil),     // 4: DataTypeRes
}
var file_profiling_proto_depIdxs = []int32{
	0, // 0: DataStatusRes.profilingSwitch:type_name -> ProfilingSwitch
	0, // 1: DataTypeReq.profilingSwitch:type_name -> ProfilingSwitch
	3, // 2: TrainingDataTrace.ModifyTrainingDataTraceSwitch:input_type -> DataTypeReq
	1, // 3: TrainingDataTrace.GetTrainingDataTraceSwitch:input_type -> DataStatusReq
	4, // 4: TrainingDataTrace.ModifyTrainingDataTraceSwitch:output_type -> DataTypeRes
	2, // 5: TrainingDataTrace.GetTrainingDataTraceSwitch:output_type -> DataStatusRes
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_profiling_proto_init() }
func file_profiling_proto_init() {
	if File_profiling_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_profiling_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfilingSwitch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profiling_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profiling_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profiling_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataTypeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profiling_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataTypeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_profiling_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profiling_proto_goTypes,
		DependencyIndexes: file_profiling_proto_depIdxs,
		MessageInfos:      file_profiling_proto_msgTypes,
	}.Build()
	File_profiling_proto = out.File
	file_profiling_proto_rawDesc = nil
	file_profiling_proto_goTypes = nil
	file_profiling_proto_depIdxs = nil
}
