// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: config.proto

package config

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Config_Register_FullMethodName           = "/config.Config/Register"
	Config_SubscribeRankTable_FullMethodName = "/config.Config/SubscribeRankTable"
)

// ConfigClient is the client API for Config service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigClient interface {
	Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error)
	SubscribeRankTable(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Config_SubscribeRankTableClient, error)
}

type configClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigClient(cc grpc.ClientConnInterface) ConfigClient {
	return &configClient{cc}
}

func (c *configClient) Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Config_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) SubscribeRankTable(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Config_SubscribeRankTableClient, error) {
	stream, err := c.cc.NewStream(ctx, &Config_ServiceDesc.Streams[0], Config_SubscribeRankTable_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &configSubscribeRankTableClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Config_SubscribeRankTableClient interface {
	Recv() (*RankTableStream, error)
	grpc.ClientStream
}

type configSubscribeRankTableClient struct {
	grpc.ClientStream
}

func (x *configSubscribeRankTableClient) Recv() (*RankTableStream, error) {
	m := new(RankTableStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConfigServer is the server API for Config service.
// All implementations must embed UnimplementedConfigServer
// for forward compatibility
type ConfigServer interface {
	Register(context.Context, *ClientInfo) (*Status, error)
	SubscribeRankTable(*ClientInfo, Config_SubscribeRankTableServer) error
	mustEmbedUnimplementedConfigServer()
}

// UnimplementedConfigServer must be embedded to have forward compatible implementations.
type UnimplementedConfigServer struct {
}

func (UnimplementedConfigServer) Register(context.Context, *ClientInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedConfigServer) SubscribeRankTable(*ClientInfo, Config_SubscribeRankTableServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeRankTable not implemented")
}
func (UnimplementedConfigServer) mustEmbedUnimplementedConfigServer() {}

// UnsafeConfigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServer will
// result in compilation errors.
type UnsafeConfigServer interface {
	mustEmbedUnimplementedConfigServer()
}

func RegisterConfigServer(s grpc.ServiceRegistrar, srv ConfigServer) {
	s.RegisterService(&Config_ServiceDesc, srv)
}

func _Config_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Config_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServer).Register(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Config_SubscribeRankTable_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigServer).SubscribeRankTable(m, &configSubscribeRankTableServer{stream})
}

type Config_SubscribeRankTableServer interface {
	Send(*RankTableStream) error
	grpc.ServerStream
}

type configSubscribeRankTableServer struct {
	grpc.ServerStream
}

func (x *configSubscribeRankTableServer) Send(m *RankTableStream) error {
	return x.ServerStream.SendMsg(m)
}

// Config_ServiceDesc is the grpc.ServiceDesc for Config service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Config_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config.Config",
	HandlerType: (*ConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Config_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRankTable",
			Handler:       _Config_SubscribeRankTable_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "config.proto",
}
