#!/usr/bin/env python
# coding=utf-8
# This file was automatically generated by SWIG.
# Version 4.2.1
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.
# Copyright (c) Huawei Technologies Co., Ltd. 2024. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""c to python API"""


class closeable_file(object):
    def close(self):
        return _c2python_api.closeable_file_close(self)

    def initialize(self):
        return _c2python_api.closeable_file_initialize(self)


class readable(closeable_file):
    def read(self, buffer, count, offset):
        return _c2python_api.readable_read(self, buffer, count, offset)

    def multi_read(self, read_vector):
        return _c2python_api.readable_multi_read(self, read_vector)

    def size(self):
        return _c2python_api.readable_size(self)


class writeable(closeable_file):
    def write(self, buffer, count):
        return _c2python_api.writeable_write(self, buffer, count)

    def write_list(self, buffers):
        return _c2python_api.writeable_write_list(self, buffers)

    def drop(self):
        return _c2python_api.writeable_drop(self)

    def flush(self):
        return _c2python_api.writeable_flush(self)


class readable_file(readable):
    def open(self):
        return _c2python_api.readable_file_open(self)

    def read(self, buffer, count, offset):
        return _c2python_api.readable_file_read(self, buffer, count, offset)

    def multi_read(self, read_vector):
        return _c2python_api.readable_file_multi_read(self, read_vector)

    def close(self):
        return _c2python_api.readable_file_close(self)

    def size(self):
        return _c2python_api.readable_file_size(self)


class freadable_file(readable):
    def open(self):
        return _c2python_api.freadable_file_open(self)

    def read(self, buffer, count, offset):
        return _c2python_api.freadable_file_read(self, buffer, count, offset)

    def multi_read(self, read_vector):
        return _c2python_api.freadable_file_multi_read(self, read_vector)

    def close(self):
        return _c2python_api.freadable_file_close(self)

    def size(self):
        return _c2python_api.freadable_file_size(self)


class nds_readable_file(readable):
    def open(self):
        return _c2python_api.nds_readable_file_open(self)

    def read(self, buffer, count, offset):
        return _c2python_api.nds_readable_file_read(self, buffer, count, offset)

    def multi_read(self, read_vector):
        return _c2python_api.nds_readable_file_multi_read(self, read_vector)

    def close(self):
        return _c2python_api.nds_readable_file_close(self)

    def size(self):
        return _c2python_api.nds_readable_file_size(self)


class writeable_file(writeable):
    def create(self):
        return _c2python_api.writeable_file_create(self)

    def write(self, buffer, count):
        return _c2python_api.writeable_file_write(self, buffer, count)

    def write_list(self, buffers):
        return _c2python_api.writeable_file_write_list(self, buffers)

    def close(self):
        return _c2python_api.writeable_file_close(self)

    def drop(self):
        return _c2python_api.writeable_file_drop(self)

    def flush(self):
        return _c2python_api.writeable_file_flush(self)


class fwriteable_file(writeable):
    def create(self):
        return _c2python_api.fwriteable_file_create(self)

    def write(self, buffer, count):
        return _c2python_api.fwriteable_file_write(self, buffer, count)

    def write_list(self, buffers):
        return _c2python_api.fwriteable_file_write_list(self, buffers)

    def close(self):
        return _c2python_api.fwriteable_file_close(self)

    def drop(self):
        return _c2python_api.fwriteable_file_drop(self)

    def remove_stg_file(self):
        return _c2python_api.fwriteable_file_remove_stg_file(self)

    def flush(self):
        return _c2python_api.fwriteable_file_flush(self)


def preload(paths):
    return _c2python_api.preload(paths)


def link(source, target):
    return _c2python_api.link(source, target)


def initialize(server_info_param):
    return _c2python_api.initialize(server_info_param)


def un_initialize():
    return _c2python_api.un_initialize()


def check_background_task():
    return _c2python_api.check_background_task()


class callback_receiver(object):
    def check_dir_callback(self, result, param):
        return _c2python_api.callback_receiver_check_dir_callback(self, result, param)


def init_callback_handler(handler):
    return _c2python_api.init_callback_handler(handler)


def handle_check_dir_callback(result, callback_param):
    return _c2python_api.handle_check_dir_callback(result, callback_param)


def register_checker(dir_info, callback_param, timeout_sec):
    return _c2python_api.register_checker(dir_info, callback_param, timeout_sec)

