// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: job.proto

package job

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Job_Register_FullMethodName                      = "/job.Job/Register"
	Job_SubscribeJobSummarySignal_FullMethodName     = "/job.Job/SubscribeJobSummarySignal"
	Job_SubscribeJobSummarySignalList_FullMethodName = "/job.Job/SubscribeJobSummarySignalList"
)

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobClient interface {
	Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error)
	SubscribeJobSummarySignal(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Job_SubscribeJobSummarySignalClient, error)
	SubscribeJobSummarySignalList(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Job_SubscribeJobSummarySignalListClient, error)
}

type jobClient struct {
	cc grpc.ClientConnInterface
}

func NewJobClient(cc grpc.ClientConnInterface) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Job_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) SubscribeJobSummarySignal(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Job_SubscribeJobSummarySignalClient, error) {
	stream, err := c.cc.NewStream(ctx, &Job_ServiceDesc.Streams[0], Job_SubscribeJobSummarySignal_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &jobSubscribeJobSummarySignalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Job_SubscribeJobSummarySignalClient interface {
	Recv() (*JobSummarySignal, error)
	grpc.ClientStream
}

type jobSubscribeJobSummarySignalClient struct {
	grpc.ClientStream
}

func (x *jobSubscribeJobSummarySignalClient) Recv() (*JobSummarySignal, error) {
	m := new(JobSummarySignal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobClient) SubscribeJobSummarySignalList(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Job_SubscribeJobSummarySignalListClient, error) {
	stream, err := c.cc.NewStream(ctx, &Job_ServiceDesc.Streams[1], Job_SubscribeJobSummarySignalList_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &jobSubscribeJobSummarySignalListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Job_SubscribeJobSummarySignalListClient interface {
	Recv() (*JobSummarySignalList, error)
	grpc.ClientStream
}

type jobSubscribeJobSummarySignalListClient struct {
	grpc.ClientStream
}

func (x *jobSubscribeJobSummarySignalListClient) Recv() (*JobSummarySignalList, error) {
	m := new(JobSummarySignalList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JobServer is the server API for Job service.
// All implementations must embed UnimplementedJobServer
// for forward compatibility
type JobServer interface {
	Register(context.Context, *ClientInfo) (*Status, error)
	SubscribeJobSummarySignal(*ClientInfo, Job_SubscribeJobSummarySignalServer) error
	SubscribeJobSummarySignalList(*ClientInfo, Job_SubscribeJobSummarySignalListServer) error
	mustEmbedUnimplementedJobServer()
}

// UnimplementedJobServer must be embedded to have forward compatible implementations.
type UnimplementedJobServer struct {
}

func (UnimplementedJobServer) Register(context.Context, *ClientInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedJobServer) SubscribeJobSummarySignal(*ClientInfo, Job_SubscribeJobSummarySignalServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeJobSummarySignal not implemented")
}
func (UnimplementedJobServer) SubscribeJobSummarySignalList(*ClientInfo, Job_SubscribeJobSummarySignalListServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeJobSummarySignalList not implemented")
}
func (UnimplementedJobServer) mustEmbedUnimplementedJobServer() {}

// UnsafeJobServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobServer will
// result in compilation errors.
type UnsafeJobServer interface {
	mustEmbedUnimplementedJobServer()
}

func RegisterJobServer(s grpc.ServiceRegistrar, srv JobServer) {
	s.RegisterService(&Job_ServiceDesc, srv)
}

func _Job_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Job_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Register(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_SubscribeJobSummarySignal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServer).SubscribeJobSummarySignal(m, &jobSubscribeJobSummarySignalServer{stream})
}

type Job_SubscribeJobSummarySignalServer interface {
	Send(*JobSummarySignal) error
	grpc.ServerStream
}

type jobSubscribeJobSummarySignalServer struct {
	grpc.ServerStream
}

func (x *jobSubscribeJobSummarySignalServer) Send(m *JobSummarySignal) error {
	return x.ServerStream.SendMsg(m)
}

func _Job_SubscribeJobSummarySignalList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServer).SubscribeJobSummarySignalList(m, &jobSubscribeJobSummarySignalListServer{stream})
}

type Job_SubscribeJobSummarySignalListServer interface {
	Send(*JobSummarySignalList) error
	grpc.ServerStream
}

type jobSubscribeJobSummarySignalListServer struct {
	grpc.ServerStream
}

func (x *jobSubscribeJobSummarySignalListServer) Send(m *JobSummarySignalList) error {
	return x.ServerStream.SendMsg(m)
}

// Job_ServiceDesc is the grpc.ServiceDesc for Job service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Job_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Job_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeJobSummarySignal",
			Handler:       _Job_SubscribeJobSummarySignal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeJobSummarySignalList",
			Handler:       _Job_SubscribeJobSummarySignalList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "job.proto",
}
