// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: fault.proto

package fault

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Fault_Register_FullMethodName                = "/fault.Fault/Register"
	Fault_SubscribeFaultMsgSignal_FullMethodName = "/fault.Fault/SubscribeFaultMsgSignal"
)

// FaultClient is the client API for Fault service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaultClient interface {
	Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error)
	SubscribeFaultMsgSignal(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Fault_SubscribeFaultMsgSignalClient, error)
}

type faultClient struct {
	cc grpc.ClientConnInterface
}

func NewFaultClient(cc grpc.ClientConnInterface) FaultClient {
	return &faultClient{cc}
}

func (c *faultClient) Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Fault_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faultClient) SubscribeFaultMsgSignal(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Fault_SubscribeFaultMsgSignalClient, error) {
	stream, err := c.cc.NewStream(ctx, &Fault_ServiceDesc.Streams[0], Fault_SubscribeFaultMsgSignal_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &faultSubscribeFaultMsgSignalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fault_SubscribeFaultMsgSignalClient interface {
	Recv() (*FaultMsgSignal, error)
	grpc.ClientStream
}

type faultSubscribeFaultMsgSignalClient struct {
	grpc.ClientStream
}

func (x *faultSubscribeFaultMsgSignalClient) Recv() (*FaultMsgSignal, error) {
	m := new(FaultMsgSignal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FaultServer is the server API for Fault service.
// All implementations must embed UnimplementedFaultServer
// for forward compatibility
type FaultServer interface {
	Register(context.Context, *ClientInfo) (*Status, error)
	SubscribeFaultMsgSignal(*ClientInfo, Fault_SubscribeFaultMsgSignalServer) error
	mustEmbedUnimplementedFaultServer()
}

// UnimplementedFaultServer must be embedded to have forward compatible implementations.
type UnimplementedFaultServer struct {
}

func (UnimplementedFaultServer) Register(context.Context, *ClientInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedFaultServer) SubscribeFaultMsgSignal(*ClientInfo, Fault_SubscribeFaultMsgSignalServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeFaultMsgSignal not implemented")
}
func (UnimplementedFaultServer) mustEmbedUnimplementedFaultServer() {}

// UnsafeFaultServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaultServer will
// result in compilation errors.
type UnsafeFaultServer interface {
	mustEmbedUnimplementedFaultServer()
}

func RegisterFaultServer(s grpc.ServiceRegistrar, srv FaultServer) {
	s.RegisterService(&Fault_ServiceDesc, srv)
}

func _Fault_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaultServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fault_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaultServer).Register(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fault_SubscribeFaultMsgSignal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FaultServer).SubscribeFaultMsgSignal(m, &faultSubscribeFaultMsgSignalServer{stream})
}

type Fault_SubscribeFaultMsgSignalServer interface {
	Send(*FaultMsgSignal) error
	grpc.ServerStream
}

type faultSubscribeFaultMsgSignalServer struct {
	grpc.ServerStream
}

func (x *faultSubscribeFaultMsgSignalServer) Send(m *FaultMsgSignal) error {
	return x.ServerStream.SendMsg(m)
}

// Fault_ServiceDesc is the grpc.ServiceDesc for Fault service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fault_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fault.Fault",
	HandlerType: (*FaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Fault_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeFaultMsgSignal",
			Handler:       _Fault_SubscribeFaultMsgSignal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fault.proto",
}
