// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fault.proto

package fault

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FaultQueryResult struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string          `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	FaultSignal          *FaultMsgSignal `protobuf:"bytes,3,opt,name=faultSignal,proto3" json:"faultSignal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FaultQueryResult) Reset()         { *m = FaultQueryResult{} }
func (m *FaultQueryResult) String() string { return proto.CompactTextString(m) }
func (*FaultQueryResult) ProtoMessage()    {}
func (*FaultQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6b57b59ad5d7d5, []int{0}
}

func (m *FaultQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaultQueryResult.Unmarshal(m, b)
}
func (m *FaultQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaultQueryResult.Marshal(b, m, deterministic)
}
func (m *FaultQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaultQueryResult.Merge(m, src)
}
func (m *FaultQueryResult) XXX_Size() int {
	return xxx_messageInfo_FaultQueryResult.Size(m)
}
func (m *FaultQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FaultQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_FaultQueryResult proto.InternalMessageInfo

func (m *FaultQueryResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FaultQueryResult) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *FaultQueryResult) GetFaultSignal() *FaultMsgSignal {
	if m != nil {
		return m.FaultSignal
	}
	return nil
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6b57b59ad5d7d5, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ClientInfo struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6b57b59ad5d7d5, []int{2}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ClientInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type FaultMsgSignal struct {
	Uuid                 string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	JobId                string           `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	SignalType           string           `protobuf:"bytes,3,opt,name=signalType,proto3" json:"signalType,omitempty"`
	NodeFaultInfo        []*NodeFaultInfo `protobuf:"bytes,4,rep,name=nodeFaultInfo,proto3" json:"nodeFaultInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FaultMsgSignal) Reset()         { *m = FaultMsgSignal{} }
func (m *FaultMsgSignal) String() string { return proto.CompactTextString(m) }
func (*FaultMsgSignal) ProtoMessage()    {}
func (*FaultMsgSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6b57b59ad5d7d5, []int{3}
}

func (m *FaultMsgSignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaultMsgSignal.Unmarshal(m, b)
}
func (m *FaultMsgSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaultMsgSignal.Marshal(b, m, deterministic)
}
func (m *FaultMsgSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaultMsgSignal.Merge(m, src)
}
func (m *FaultMsgSignal) XXX_Size() int {
	return xxx_messageInfo_FaultMsgSignal.Size(m)
}
func (m *FaultMsgSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_FaultMsgSignal.DiscardUnknown(m)
}

var xxx_messageInfo_FaultMsgSignal proto.InternalMessageInfo

func (m *FaultMsgSignal) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *FaultMsgSignal) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *FaultMsgSignal) GetSignalType() string {
	if m != nil {
		return m.SignalType
	}
	return ""
}

func (m *FaultMsgSignal) GetNodeFaultInfo() []*NodeFaultInfo {
	if m != nil {
		return m.NodeFaultInfo
	}
	return nil
}

type NodeFaultInfo struct {
	NodeName             string             `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	NodeIP               string             `protobuf:"bytes,2,opt,name=nodeIP,proto3" json:"nodeIP,omitempty"`
	NodeSN               string             `protobuf:"bytes,3,opt,name=nodeSN,proto3" json:"nodeSN,omitempty"`
	FaultLevel           string             `protobuf:"bytes,4,opt,name=faultLevel,proto3" json:"faultLevel,omitempty"`
	FaultDevice          []*DeviceFaultInfo `protobuf:"bytes,5,rep,name=faultDevice,proto3" json:"faultDevice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NodeFaultInfo) Reset()         { *m = NodeFaultInfo{} }
func (m *NodeFaultInfo) String() string { return proto.CompactTextString(m) }
func (*NodeFaultInfo) ProtoMessage()    {}
func (*NodeFaultInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6b57b59ad5d7d5, []int{4}
}

func (m *NodeFaultInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeFaultInfo.Unmarshal(m, b)
}
func (m *NodeFaultInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeFaultInfo.Marshal(b, m, deterministic)
}
func (m *NodeFaultInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeFaultInfo.Merge(m, src)
}
func (m *NodeFaultInfo) XXX_Size() int {
	return xxx_messageInfo_NodeFaultInfo.Size(m)
}
func (m *NodeFaultInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeFaultInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeFaultInfo proto.InternalMessageInfo

func (m *NodeFaultInfo) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeFaultInfo) GetNodeIP() string {
	if m != nil {
		return m.NodeIP
	}
	return ""
}

func (m *NodeFaultInfo) GetNodeSN() string {
	if m != nil {
		return m.NodeSN
	}
	return ""
}

func (m *NodeFaultInfo) GetFaultLevel() string {
	if m != nil {
		return m.FaultLevel
	}
	return ""
}

func (m *NodeFaultInfo) GetFaultDevice() []*DeviceFaultInfo {
	if m != nil {
		return m.FaultDevice
	}
	return nil
}

type DeviceFaultInfo struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	DeviceType           string   `protobuf:"bytes,2,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	FaultCodes           []string `protobuf:"bytes,3,rep,name=faultCodes,proto3" json:"faultCodes,omitempty"`
	FaultLevel           string   `protobuf:"bytes,4,opt,name=faultLevel,proto3" json:"faultLevel,omitempty"`
	FaultType            []string `protobuf:"bytes,5,rep,name=faultType,proto3" json:"faultType,omitempty"`
	FaultReason          []string `protobuf:"bytes,6,rep,name=faultReason,proto3" json:"faultReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceFaultInfo) Reset()         { *m = DeviceFaultInfo{} }
func (m *DeviceFaultInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceFaultInfo) ProtoMessage()    {}
func (*DeviceFaultInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f6b57b59ad5d7d5, []int{5}
}

func (m *DeviceFaultInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceFaultInfo.Unmarshal(m, b)
}
func (m *DeviceFaultInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceFaultInfo.Marshal(b, m, deterministic)
}
func (m *DeviceFaultInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceFaultInfo.Merge(m, src)
}
func (m *DeviceFaultInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceFaultInfo.Size(m)
}
func (m *DeviceFaultInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceFaultInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceFaultInfo proto.InternalMessageInfo

func (m *DeviceFaultInfo) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceFaultInfo) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DeviceFaultInfo) GetFaultCodes() []string {
	if m != nil {
		return m.FaultCodes
	}
	return nil
}

func (m *DeviceFaultInfo) GetFaultLevel() string {
	if m != nil {
		return m.FaultLevel
	}
	return ""
}

func (m *DeviceFaultInfo) GetFaultType() []string {
	if m != nil {
		return m.FaultType
	}
	return nil
}

func (m *DeviceFaultInfo) GetFaultReason() []string {
	if m != nil {
		return m.FaultReason
	}
	return nil
}

func init() {
	proto.RegisterType((*FaultQueryResult)(nil), "fault.FaultQueryResult")
	proto.RegisterType((*Status)(nil), "fault.Status")
	proto.RegisterType((*ClientInfo)(nil), "fault.ClientInfo")
	proto.RegisterType((*FaultMsgSignal)(nil), "fault.FaultMsgSignal")
	proto.RegisterType((*NodeFaultInfo)(nil), "fault.NodeFaultInfo")
	proto.RegisterType((*DeviceFaultInfo)(nil), "fault.DeviceFaultInfo")
}

func init() {
	proto.RegisterFile("fault.proto", fileDescriptor_1f6b57b59ad5d7d5)
}

var fileDescriptor_1f6b57b59ad5d7d5 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xe3, 0x26, 0x1b, 0xba, 0x13, 0x05, 0xa8, 0x55, 0xda, 0x55, 0x85, 0xd0, 0xca, 0xa7,
	0x9c, 0xa2, 0x2a, 0x48, 0x80, 0xe0, 0x04, 0x45, 0x54, 0x91, 0x20, 0x02, 0x87, 0x13, 0xb7, 0x4d,
	0x76, 0x1a, 0x2d, 0x5a, 0xd6, 0xd5, 0xda, 0x5b, 0xa9, 0x2f, 0xc2, 0x9b, 0xf0, 0x04, 0x9c, 0x79,
	0x27, 0xe4, 0xb1, 0xb3, 0xeb, 0x54, 0x95, 0xd2, 0xdb, 0xcc, 0xe7, 0x99, 0xcf, 0xbf, 0xf1, 0x1f,
	0x18, 0x5d, 0x65, 0x4d, 0x69, 0xa6, 0xd7, 0xb5, 0x32, 0x8a, 0x47, 0x94, 0x08, 0x0d, 0x4f, 0x3f,
	0xd9, 0xe0, 0x5b, 0x83, 0xf5, 0xad, 0x44, 0xdd, 0x94, 0x86, 0x73, 0x18, 0xac, 0x55, 0x8e, 0x09,
	0x4b, 0xd9, 0x24, 0x92, 0x14, 0x5b, 0xad, 0xa8, 0xae, 0x54, 0x72, 0x90, 0xb2, 0x49, 0x2c, 0x29,
	0xe6, 0xaf, 0xbd, 0xe3, 0xb2, 0xd8, 0x54, 0x59, 0x99, 0xf4, 0x53, 0x36, 0x19, 0xcd, 0x9e, 0x4d,
	0xdd, 0x2e, 0xe4, 0xfa, 0x45, 0x6f, 0xdc, 0xa2, 0x0c, 0x2b, 0xc5, 0x39, 0x0c, 0x97, 0x26, 0x33,
	0x8d, 0x7e, 0xe8, 0x56, 0xe2, 0x15, 0xc0, 0x45, 0x59, 0x60, 0x65, 0xe6, 0x76, 0xe3, 0x63, 0x88,
	0x7e, 0xaa, 0xd5, 0x3c, 0xa7, 0xb6, 0x58, 0xba, 0xc4, 0xf6, 0xd5, 0xaa, 0xc4, 0x6d, 0x9f, 0x8d,
	0xc5, 0x6f, 0x06, 0x8f, 0x77, 0x49, 0x6c, 0x59, 0xd3, 0x14, 0xdb, 0x5e, 0x8a, 0x3b, 0xc3, 0x83,
	0xd0, 0xf0, 0x05, 0x80, 0xa6, 0x9e, 0xef, 0xb7, 0xd7, 0x48, 0xe3, 0xc5, 0x32, 0x50, 0xf8, 0x5b,
	0x18, 0x57, 0x2a, 0x47, 0xf2, 0xb7, 0x5c, 0xc9, 0x20, 0xed, 0x4f, 0x46, 0xb3, 0x63, 0x7f, 0x02,
	0x8b, 0x70, 0x4d, 0xee, 0x96, 0x8a, 0x3f, 0x0c, 0xc6, 0x3b, 0x05, 0xfc, 0x0c, 0x0e, 0x6d, 0xc9,
	0x22, 0xfb, 0x85, 0x9e, 0xad, 0xcd, 0xf9, 0x09, 0x0c, 0x6d, 0x3c, 0xff, 0xea, 0x01, 0x7d, 0xb6,
	0xd5, 0x97, 0x0b, 0x4f, 0xe7, 0x33, 0x4b, 0x4e, 0x0c, 0x9f, 0xf1, 0x06, 0xcb, 0x64, 0xe0, 0xc8,
	0x3b, 0x85, 0xbf, 0xf1, 0x37, 0xf7, 0x11, 0x6f, 0x8a, 0x35, 0x26, 0x11, 0x71, 0x9f, 0x78, 0x6e,
	0x27, 0x76, 0xe4, 0x61, 0xa9, 0xf8, 0xc7, 0xe0, 0xc9, 0x9d, 0x02, 0x4b, 0x9e, 0x93, 0xd4, 0xde,
	0x48, 0x9b, 0x5b, 0x12, 0x17, 0xd3, 0x19, 0x3a, 0xfa, 0x40, 0x69, 0x49, 0x2f, 0x54, 0x8e, 0x3a,
	0xe9, 0xa7, 0xfd, 0x96, 0x94, 0x94, 0xbd, 0x93, 0x3c, 0x87, 0x98, 0x32, 0xb2, 0x8f, 0xa8, 0xbd,
	0x13, 0x78, 0xea, 0xe7, 0x94, 0x98, 0x69, 0x55, 0x25, 0x43, 0x5a, 0x0f, 0xa5, 0xd9, 0x5f, 0x06,
	0x11, 0x4d, 0xc2, 0xa7, 0x70, 0x28, 0x71, 0x53, 0x68, 0x83, 0x35, 0x3f, 0xf2, 0x47, 0xd1, 0xbd,
	0xb9, 0xb3, 0xb1, 0x97, 0xdc, 0xc3, 0x15, 0x3d, 0x7e, 0x09, 0xa7, 0xcb, 0x66, 0xa5, 0xd7, 0x75,
	0xb1, 0xc2, 0x3b, 0x4f, 0xec, 0x9e, 0xf6, 0xfb, 0xbf, 0x85, 0xe8, 0x9d, 0x33, 0xfe, 0x1e, 0x8e,
	0x2e, 0xd1, 0xec, 0xb7, 0x38, 0x0d, 0x2d, 0x82, 0xff, 0x2a, 0x7a, 0x1f, 0xe2, 0x1f, 0x8f, 0xa6,
	0xef, 0x68, 0x75, 0x35, 0xa4, 0xef, 0xfd, 0xf2, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x25,
	0x61, 0x7b, 0xed, 0x03, 0x00, 0x00,
}
