// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recover.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ClientInfo struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{1}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ClientInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type FaultRank struct {
	RankId               string   `protobuf:"bytes,1,opt,name=rankId,proto3" json:"rankId,omitempty"`
	FaultType            string   `protobuf:"bytes,2,opt,name=faultType,proto3" json:"faultType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaultRank) Reset()         { *m = FaultRank{} }
func (m *FaultRank) String() string { return proto.CompactTextString(m) }
func (*FaultRank) ProtoMessage()    {}
func (*FaultRank) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{2}
}

func (m *FaultRank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaultRank.Unmarshal(m, b)
}
func (m *FaultRank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaultRank.Marshal(b, m, deterministic)
}
func (m *FaultRank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaultRank.Merge(m, src)
}
func (m *FaultRank) XXX_Size() int {
	return xxx_messageInfo_FaultRank.Size(m)
}
func (m *FaultRank) XXX_DiscardUnknown() {
	xxx_messageInfo_FaultRank.DiscardUnknown(m)
}

var xxx_messageInfo_FaultRank proto.InternalMessageInfo

func (m *FaultRank) GetRankId() string {
	if m != nil {
		return m.RankId
	}
	return ""
}

func (m *FaultRank) GetFaultType() string {
	if m != nil {
		return m.FaultType
	}
	return ""
}

type ProcessManageSignal struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	JobId                string       `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	SignalType           string       `protobuf:"bytes,3,opt,name=signalType,proto3" json:"signalType,omitempty"`
	Actions              []string     `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,5,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	ChangeStrategy       string       `protobuf:"bytes,6,opt,name=changeStrategy,proto3" json:"changeStrategy,omitempty"`
	Timeout              int64        `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProcessManageSignal) Reset()         { *m = ProcessManageSignal{} }
func (m *ProcessManageSignal) String() string { return proto.CompactTextString(m) }
func (*ProcessManageSignal) ProtoMessage()    {}
func (*ProcessManageSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{3}
}

func (m *ProcessManageSignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessManageSignal.Unmarshal(m, b)
}
func (m *ProcessManageSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessManageSignal.Marshal(b, m, deterministic)
}
func (m *ProcessManageSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessManageSignal.Merge(m, src)
}
func (m *ProcessManageSignal) XXX_Size() int {
	return xxx_messageInfo_ProcessManageSignal.Size(m)
}
func (m *ProcessManageSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessManageSignal.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessManageSignal proto.InternalMessageInfo

func (m *ProcessManageSignal) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ProcessManageSignal) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ProcessManageSignal) GetSignalType() string {
	if m != nil {
		return m.SignalType
	}
	return ""
}

func (m *ProcessManageSignal) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *ProcessManageSignal) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

func (m *ProcessManageSignal) GetChangeStrategy() string {
	if m != nil {
		return m.ChangeStrategy
	}
	return ""
}

func (m *ProcessManageSignal) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type StopCompleteRequest struct {
	JobId                string       `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Status               *Status      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,3,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StopCompleteRequest) Reset()         { *m = StopCompleteRequest{} }
func (m *StopCompleteRequest) String() string { return proto.CompactTextString(m) }
func (*StopCompleteRequest) ProtoMessage()    {}
func (*StopCompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{4}
}

func (m *StopCompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopCompleteRequest.Unmarshal(m, b)
}
func (m *StopCompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopCompleteRequest.Marshal(b, m, deterministic)
}
func (m *StopCompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopCompleteRequest.Merge(m, src)
}
func (m *StopCompleteRequest) XXX_Size() int {
	return xxx_messageInfo_StopCompleteRequest.Size(m)
}
func (m *StopCompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopCompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopCompleteRequest proto.InternalMessageInfo

func (m *StopCompleteRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *StopCompleteRequest) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StopCompleteRequest) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

type RecoverStrategyRequest struct {
	JobId                string       `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,2,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	Strategies           []string     `protobuf:"bytes,3,rep,name=strategies,proto3" json:"strategies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RecoverStrategyRequest) Reset()         { *m = RecoverStrategyRequest{} }
func (m *RecoverStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverStrategyRequest) ProtoMessage()    {}
func (*RecoverStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{5}
}

func (m *RecoverStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverStrategyRequest.Unmarshal(m, b)
}
func (m *RecoverStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverStrategyRequest.Marshal(b, m, deterministic)
}
func (m *RecoverStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverStrategyRequest.Merge(m, src)
}
func (m *RecoverStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverStrategyRequest.Size(m)
}
func (m *RecoverStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverStrategyRequest proto.InternalMessageInfo

func (m *RecoverStrategyRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RecoverStrategyRequest) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

func (m *RecoverStrategyRequest) GetStrategies() []string {
	if m != nil {
		return m.Strategies
	}
	return nil
}

type RecoverStatusRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Strategy             string   `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverStatusRequest) Reset()         { *m = RecoverStatusRequest{} }
func (m *RecoverStatusRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverStatusRequest) ProtoMessage()    {}
func (*RecoverStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{6}
}

func (m *RecoverStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverStatusRequest.Unmarshal(m, b)
}
func (m *RecoverStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverStatusRequest.Marshal(b, m, deterministic)
}
func (m *RecoverStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverStatusRequest.Merge(m, src)
}
func (m *RecoverStatusRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverStatusRequest.Size(m)
}
func (m *RecoverStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverStatusRequest proto.InternalMessageInfo

func (m *RecoverStatusRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RecoverStatusRequest) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RecoverStatusRequest) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

type ProcessFaultRequest struct {
	JobId                string       `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,2,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProcessFaultRequest) Reset()         { *m = ProcessFaultRequest{} }
func (m *ProcessFaultRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessFaultRequest) ProtoMessage()    {}
func (*ProcessFaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{7}
}

func (m *ProcessFaultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessFaultRequest.Unmarshal(m, b)
}
func (m *ProcessFaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessFaultRequest.Marshal(b, m, deterministic)
}
func (m *ProcessFaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessFaultRequest.Merge(m, src)
}
func (m *ProcessFaultRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessFaultRequest.Size(m)
}
func (m *ProcessFaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessFaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessFaultRequest proto.InternalMessageInfo

func (m *ProcessFaultRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ProcessFaultRequest) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

type SwitchNicResponse struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchNicResponse) Reset()         { *m = SwitchNicResponse{} }
func (m *SwitchNicResponse) String() string { return proto.CompactTextString(m) }
func (*SwitchNicResponse) ProtoMessage()    {}
func (*SwitchNicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{8}
}

func (m *SwitchNicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchNicResponse.Unmarshal(m, b)
}
func (m *SwitchNicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchNicResponse.Marshal(b, m, deterministic)
}
func (m *SwitchNicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchNicResponse.Merge(m, src)
}
func (m *SwitchNicResponse) XXX_Size() int {
	return xxx_messageInfo_SwitchNicResponse.Size(m)
}
func (m *SwitchNicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchNicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchNicResponse proto.InternalMessageInfo

func (m *SwitchNicResponse) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *SwitchNicResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SwitchNicRequest struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchNicRequest) Reset()         { *m = SwitchNicRequest{} }
func (m *SwitchNicRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchNicRequest) ProtoMessage()    {}
func (*SwitchNicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{9}
}

func (m *SwitchNicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchNicRequest.Unmarshal(m, b)
}
func (m *SwitchNicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchNicRequest.Marshal(b, m, deterministic)
}
func (m *SwitchNicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchNicRequest.Merge(m, src)
}
func (m *SwitchNicRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchNicRequest.Size(m)
}
func (m *SwitchNicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchNicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchNicRequest proto.InternalMessageInfo

func (m *SwitchNicRequest) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type SwitchNics struct {
	JobID                string                 `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	NicOps               map[string]*DeviceList `protobuf:"bytes,2,rep,name=nicOps,proto3" json:"nicOps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SwitchNics) Reset()         { *m = SwitchNics{} }
func (m *SwitchNics) String() string { return proto.CompactTextString(m) }
func (*SwitchNics) ProtoMessage()    {}
func (*SwitchNics) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{10}
}

func (m *SwitchNics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchNics.Unmarshal(m, b)
}
func (m *SwitchNics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchNics.Marshal(b, m, deterministic)
}
func (m *SwitchNics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchNics.Merge(m, src)
}
func (m *SwitchNics) XXX_Size() int {
	return xxx_messageInfo_SwitchNics.Size(m)
}
func (m *SwitchNics) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchNics.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchNics proto.InternalMessageInfo

func (m *SwitchNics) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *SwitchNics) GetNicOps() map[string]*DeviceList {
	if m != nil {
		return m.NicOps
	}
	return nil
}

type SwitchStatus struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	RankID               string   `protobuf:"bytes,2,opt,name=rankID,proto3" json:"rankID,omitempty"`
	Res                  bool     `protobuf:"varint,3,opt,name=res,proto3" json:"res,omitempty"`
	Msg                  string   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchStatus) Reset()         { *m = SwitchStatus{} }
func (m *SwitchStatus) String() string { return proto.CompactTextString(m) }
func (*SwitchStatus) ProtoMessage()    {}
func (*SwitchStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{11}
}

func (m *SwitchStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchStatus.Unmarshal(m, b)
}
func (m *SwitchStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchStatus.Marshal(b, m, deterministic)
}
func (m *SwitchStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchStatus.Merge(m, src)
}
func (m *SwitchStatus) XXX_Size() int {
	return xxx_messageInfo_SwitchStatus.Size(m)
}
func (m *SwitchStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchStatus proto.InternalMessageInfo

func (m *SwitchStatus) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *SwitchStatus) GetRankID() string {
	if m != nil {
		return m.RankID
	}
	return ""
}

func (m *SwitchStatus) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func (m *SwitchStatus) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeviceList struct {
	Dev                  []string `protobuf:"bytes,1,rep,name=dev,proto3" json:"dev,omitempty"`
	Op                   []bool   `protobuf:"varint,2,rep,packed,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceList) Reset()         { *m = DeviceList{} }
func (m *DeviceList) String() string { return proto.CompactTextString(m) }
func (*DeviceList) ProtoMessage()    {}
func (*DeviceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{12}
}

func (m *DeviceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceList.Unmarshal(m, b)
}
func (m *DeviceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceList.Marshal(b, m, deterministic)
}
func (m *DeviceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceList.Merge(m, src)
}
func (m *DeviceList) XXX_Size() int {
	return xxx_messageInfo_DeviceList.Size(m)
}
func (m *DeviceList) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceList.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceList proto.InternalMessageInfo

func (m *DeviceList) GetDev() []string {
	if m != nil {
		return m.Dev
	}
	return nil
}

func (m *DeviceList) GetOp() []bool {
	if m != nil {
		return m.Op
	}
	return nil
}

type SwitchRankList struct {
	RankID               []string `protobuf:"bytes,1,rep,name=rankID,proto3" json:"rankID,omitempty"`
	Op                   []bool   `protobuf:"varint,2,rep,packed,name=op,proto3" json:"op,omitempty"`
	JobId                string   `protobuf:"bytes,3,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchRankList) Reset()         { *m = SwitchRankList{} }
func (m *SwitchRankList) String() string { return proto.CompactTextString(m) }
func (*SwitchRankList) ProtoMessage()    {}
func (*SwitchRankList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{13}
}

func (m *SwitchRankList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchRankList.Unmarshal(m, b)
}
func (m *SwitchRankList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchRankList.Marshal(b, m, deterministic)
}
func (m *SwitchRankList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchRankList.Merge(m, src)
}
func (m *SwitchRankList) XXX_Size() int {
	return xxx_messageInfo_SwitchRankList.Size(m)
}
func (m *SwitchRankList) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchRankList.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchRankList proto.InternalMessageInfo

func (m *SwitchRankList) GetRankID() []string {
	if m != nil {
		return m.RankID
	}
	return nil
}

func (m *SwitchRankList) GetOp() []bool {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *SwitchRankList) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type SwitchResult struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchResult) Reset()         { *m = SwitchResult{} }
func (m *SwitchResult) String() string { return proto.CompactTextString(m) }
func (*SwitchResult) ProtoMessage()    {}
func (*SwitchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{14}
}

func (m *SwitchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchResult.Unmarshal(m, b)
}
func (m *SwitchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchResult.Marshal(b, m, deterministic)
}
func (m *SwitchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchResult.Merge(m, src)
}
func (m *SwitchResult) XXX_Size() int {
	return xxx_messageInfo_SwitchResult.Size(m)
}
func (m *SwitchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchResult proto.InternalMessageInfo

func (m *SwitchResult) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *SwitchResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*ClientInfo)(nil), "ClientInfo")
	proto.RegisterType((*FaultRank)(nil), "FaultRank")
	proto.RegisterType((*ProcessManageSignal)(nil), "ProcessManageSignal")
	proto.RegisterType((*StopCompleteRequest)(nil), "StopCompleteRequest")
	proto.RegisterType((*RecoverStrategyRequest)(nil), "RecoverStrategyRequest")
	proto.RegisterType((*RecoverStatusRequest)(nil), "RecoverStatusRequest")
	proto.RegisterType((*ProcessFaultRequest)(nil), "ProcessFaultRequest")
	proto.RegisterType((*SwitchNicResponse)(nil), "SwitchNicResponse")
	proto.RegisterType((*SwitchNicRequest)(nil), "SwitchNicRequest")
	proto.RegisterType((*SwitchNics)(nil), "SwitchNics")
	proto.RegisterMapType((map[string]*DeviceList)(nil), "SwitchNics.NicOpsEntry")
	proto.RegisterType((*SwitchStatus)(nil), "SwitchStatus")
	proto.RegisterType((*DeviceList)(nil), "DeviceList")
	proto.RegisterType((*SwitchRankList)(nil), "SwitchRankList")
	proto.RegisterType((*SwitchResult)(nil), "SwitchResult")
}

func init() {
	proto.RegisterFile("recover.proto", fileDescriptor_e825e73050144430)
}

var fileDescriptor_e825e73050144430 = []byte{
	// 799 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0x5d, 0xe7, 0x3b, 0x37, 0x6c, 0xd9, 0x9d, 0xa6, 0xbb, 0x56, 0xb4, 0x2a, 0x61, 0x24, 0x90,
	0xc5, 0xc3, 0x50, 0x15, 0xf1, 0x59, 0x5e, 0xa0, 0x69, 0x45, 0x25, 0x08, 0x68, 0x52, 0x09, 0x89,
	0x27, 0x1c, 0x77, 0x92, 0x0c, 0x71, 0x3d, 0xc6, 0x33, 0x0e, 0x84, 0xbf, 0xc2, 0x0f, 0xe4, 0x57,
	0x20, 0xa1, 0x19, 0x7b, 0xec, 0x49, 0x48, 0xfa, 0x02, 0x6f, 0x77, 0x3e, 0xce, 0x3d, 0xe7, 0xde,
	0x39, 0xbe, 0x32, 0x3c, 0xcf, 0x58, 0x24, 0x36, 0x2c, 0x23, 0x69, 0x26, 0x94, 0xc0, 0x17, 0xd0,
	0x99, 0xa9, 0x50, 0xe5, 0x12, 0x21, 0x68, 0x45, 0xe2, 0x81, 0xf9, 0xde, 0xd8, 0x0b, 0xda, 0xd4,
	0xc4, 0x7a, 0x8f, 0x27, 0x0b, 0xe1, 0x37, 0xc6, 0x5e, 0xd0, 0xa7, 0x26, 0xc6, 0x9f, 0x00, 0x5c,
	0xc7, 0x9c, 0x25, 0xea, 0x2e, 0x59, 0x08, 0x34, 0x84, 0xf6, 0x2f, 0x62, 0x7e, 0xf7, 0x60, 0x60,
	0x7d, 0x5a, 0x2c, 0x34, 0x2e, 0x13, 0x31, 0xb3, 0x38, 0x1d, 0xe3, 0xaf, 0xa0, 0x7f, 0x1b, 0xe6,
	0xb1, 0xa2, 0x61, 0xb2, 0x46, 0xaf, 0xa0, 0x93, 0x85, 0xc9, 0xba, 0xc2, 0x95, 0x2b, 0xf4, 0x06,
	0xfa, 0x0b, 0x7d, 0xe9, 0x7e, 0x9b, 0x5a, 0x74, 0xbd, 0x81, 0xff, 0xf2, 0xe0, 0xf4, 0x87, 0x4c,
	0x44, 0x4c, 0xca, 0xef, 0xc2, 0x24, 0x5c, 0xb2, 0x19, 0x5f, 0x26, 0x61, 0xac, 0xe9, 0xf2, 0x9c,
	0xdb, 0x5c, 0x26, 0xae, 0x85, 0x35, 0x5c, 0x61, 0xe7, 0x00, 0xd2, 0x60, 0x0c, 0x41, 0xd3, 0x1c,
	0x39, 0x3b, 0xc8, 0x87, 0x6e, 0x18, 0x29, 0x2e, 0x12, 0xe9, 0xb7, 0xc6, 0xcd, 0xa0, 0x4f, 0xed,
	0x12, 0x7d, 0x00, 0xb0, 0xb0, 0xf2, 0xa5, 0xdf, 0x1e, 0x37, 0x83, 0xc1, 0x25, 0x90, 0xaa, 0x22,
	0xea, 0x9c, 0xa2, 0xf7, 0xe1, 0x24, 0x5a, 0x85, 0xc9, 0x92, 0xcd, 0x54, 0x16, 0x2a, 0xb6, 0xdc,
	0xfa, 0x1d, 0xc3, 0xb4, 0xb7, 0xab, 0xd9, 0x14, 0x7f, 0x64, 0x22, 0x57, 0x7e, 0x77, 0xec, 0x05,
	0x4d, 0x6a, 0x97, 0xf8, 0x77, 0x38, 0x9d, 0x29, 0x91, 0x5e, 0x8b, 0xc7, 0x34, 0x66, 0x8a, 0x51,
	0xf6, 0x6b, 0xce, 0xa4, 0x3a, 0xd2, 0xed, 0x77, 0xa0, 0x23, 0xcd, 0x1b, 0x9a, 0x5a, 0x07, 0x97,
	0x5d, 0x52, 0x3c, 0x29, 0x2d, 0xb7, 0xf7, 0xb4, 0x37, 0x9f, 0xd2, 0x8e, 0xff, 0x80, 0x57, 0xb4,
	0x70, 0x88, 0x95, 0xf9, 0x34, 0xf9, 0x6e, 0xee, 0xc6, 0x93, 0x7d, 0xd1, 0xdd, 0x2f, 0x92, 0x72,
	0x56, 0xe8, 0xd0, 0xdd, 0xaf, 0x76, 0x30, 0x87, 0x61, 0xc5, 0x6d, 0x0a, 0xf8, 0x6f, 0x65, 0x8f,
	0xa0, 0x27, 0xed, 0x03, 0x14, 0x4f, 0x5d, 0xad, 0xf1, 0x8f, 0x95, 0x93, 0x0a, 0xa9, 0xff, 0x57,
	0x8d, 0xf8, 0x0a, 0x5e, 0xce, 0x7e, 0xe3, 0x2a, 0x5a, 0x4d, 0x79, 0x44, 0x99, 0x4c, 0x45, 0x22,
	0x99, 0x4d, 0x3b, 0x71, 0xd3, 0x4e, 0xd0, 0x0b, 0x68, 0x3e, 0xca, 0x65, 0x69, 0x50, 0x1d, 0xe2,
	0x00, 0x5e, 0x38, 0xe0, 0x1d, 0x49, 0xbb, 0x58, 0xfc, 0xa7, 0x07, 0x50, 0x5d, 0x95, 0x47, 0x08,
	0x3e, 0x84, 0x4e, 0xc2, 0xa3, 0xef, 0x53, 0xab, 0xf9, 0x35, 0xa9, 0x21, 0x64, 0x6a, 0x4e, 0x6e,
	0x12, 0x95, 0x6d, 0x69, 0x79, 0x6d, 0x74, 0x0b, 0x03, 0x67, 0x5b, 0x0b, 0x5c, 0xb3, 0x6d, 0x99,
	0x53, 0x87, 0xe8, 0x5d, 0x68, 0x6f, 0xc2, 0x38, 0x67, 0x65, 0xcb, 0x07, 0x64, 0xc2, 0x36, 0x3c,
	0x62, 0xdf, 0x72, 0xa9, 0x68, 0x71, 0xf2, 0x45, 0xe3, 0x33, 0x0f, 0xff, 0x0c, 0x6f, 0x15, 0x4c,
	0xe5, 0x6c, 0x39, 0x2c, 0xcf, 0x0e, 0x81, 0x49, 0xd9, 0x82, 0x72, 0xa5, 0x69, 0x33, 0xe3, 0x0f,
	0x2f, 0xe8, 0x51, 0x1d, 0xda, 0x4e, 0xb5, 0xea, 0x4e, 0x11, 0x80, 0x9a, 0x5a, 0x9f, 0x3f, 0xb0,
	0x8d, 0xef, 0x19, 0x47, 0xe9, 0x10, 0x9d, 0x40, 0x43, 0xa4, 0xa6, 0xec, 0x1e, 0x6d, 0x88, 0x14,
	0x4f, 0xe1, 0xa4, 0x50, 0xa4, 0x5f, 0xc9, 0x60, 0x6a, 0xf6, 0x02, 0x66, 0xd9, 0xf7, 0x90, 0xb5,
	0x25, 0x9a, 0x8e, 0x25, 0xf0, 0x97, 0xb6, 0x42, 0xca, 0x64, 0x1e, 0x1f, 0x33, 0x8e, 0xe6, 0x30,
	0xe7, 0xa6, 0xc2, 0x1e, 0x2d, 0x57, 0x97, 0x7f, 0xb7, 0xa0, 0x5b, 0x3a, 0x1d, 0x9d, 0x43, 0xeb,
	0x2e, 0xe1, 0x0a, 0x0d, 0x48, 0x3d, 0x56, 0x47, 0xd6, 0xcb, 0xf8, 0x19, 0xc2, 0xd0, 0xa3, 0x6c,
	0xc9, 0xa5, 0x62, 0xd9, 0xd1, 0x3b, 0x37, 0xf0, 0x66, 0x96, 0xcf, 0x65, 0x94, 0xf1, 0x39, 0x3b,
	0x34, 0x20, 0x77, 0x70, 0x43, 0x72, 0xe0, 0x0a, 0x7e, 0x76, 0xe1, 0xa1, 0x8f, 0x01, 0x51, 0x96,
	0x8a, 0x4c, 0xb9, 0xb3, 0x07, 0x0d, 0xc9, 0x81, 0x51, 0xe4, 0xb2, 0x5f, 0xc1, 0x59, 0x01, 0xdb,
	0x1b, 0x1c, 0xe8, 0x35, 0x39, 0x3c, 0x4a, 0x5c, 0xf0, 0xa7, 0x70, 0xba, 0x07, 0x36, 0x8e, 0x39,
	0x23, 0x87, 0x26, 0x81, 0x0b, 0xac, 0xc4, 0xba, 0xdf, 0x31, 0xaa, 0x8a, 0x73, 0x3f, 0x6b, 0x17,
	0x16, 0x58, 0x23, 0x4c, 0x79, 0x74, 0x9f, 0x85, 0xd1, 0x1a, 0x0d, 0x9c, 0xaf, 0x62, 0xb7, 0xa9,
	0x7e, 0xd5, 0xd4, 0xea, 0x46, 0xd9, 0xd0, 0x97, 0x64, 0xff, 0x3b, 0x1d, 0x21, 0xf2, 0xaf, 0xef,
	0xde, 0x34, 0xf5, 0x73, 0x38, 0xab, 0xd2, 0x4c, 0x85, 0xe2, 0x8b, 0x6d, 0x71, 0x6f, 0xf7, 0x51,
	0xde, 0x26, 0xbb, 0xf6, 0x34, 0xd0, 0x0b, 0x3d, 0x0f, 0xd3, 0x78, 0xeb, 0x26, 0xd6, 0x45, 0x3e,
	0x27, 0xae, 0xf7, 0x5c, 0xcd, 0xef, 0xc1, 0xe0, 0x1b, 0x16, 0xc6, 0x6a, 0x75, 0xbd, 0x62, 0xa6,
	0xb4, 0x83, 0x7e, 0xf9, 0xba, 0xf3, 0x53, 0x8b, 0x5c, 0xa5, 0xf3, 0x79, 0xc7, 0xfc, 0x04, 0x7c,
	0xf4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x7f, 0xbc, 0x0d, 0x15, 0x08, 0x00, 0x00,
}
