// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recover.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ClientInfo struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{1}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ClientInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type FaultRank struct {
	RankId               string   `protobuf:"bytes,1,opt,name=rankId,proto3" json:"rankId,omitempty"`
	FaultType            string   `protobuf:"bytes,2,opt,name=faultType,proto3" json:"faultType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaultRank) Reset()         { *m = FaultRank{} }
func (m *FaultRank) String() string { return proto.CompactTextString(m) }
func (*FaultRank) ProtoMessage()    {}
func (*FaultRank) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{2}
}

func (m *FaultRank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaultRank.Unmarshal(m, b)
}
func (m *FaultRank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaultRank.Marshal(b, m, deterministic)
}
func (m *FaultRank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaultRank.Merge(m, src)
}
func (m *FaultRank) XXX_Size() int {
	return xxx_messageInfo_FaultRank.Size(m)
}
func (m *FaultRank) XXX_DiscardUnknown() {
	xxx_messageInfo_FaultRank.DiscardUnknown(m)
}

var xxx_messageInfo_FaultRank proto.InternalMessageInfo

func (m *FaultRank) GetRankId() string {
	if m != nil {
		return m.RankId
	}
	return ""
}

func (m *FaultRank) GetFaultType() string {
	if m != nil {
		return m.FaultType
	}
	return ""
}

type ProcessManageSignal struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	JobId                string       `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	SignalType           string       `protobuf:"bytes,3,opt,name=signalType,proto3" json:"signalType,omitempty"`
	Actions              []string     `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,5,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	ChangeStrategy       string       `protobuf:"bytes,6,opt,name=changeStrategy,proto3" json:"changeStrategy,omitempty"`
	Timeout              int64        `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProcessManageSignal) Reset()         { *m = ProcessManageSignal{} }
func (m *ProcessManageSignal) String() string { return proto.CompactTextString(m) }
func (*ProcessManageSignal) ProtoMessage()    {}
func (*ProcessManageSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{3}
}

func (m *ProcessManageSignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessManageSignal.Unmarshal(m, b)
}
func (m *ProcessManageSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessManageSignal.Marshal(b, m, deterministic)
}
func (m *ProcessManageSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessManageSignal.Merge(m, src)
}
func (m *ProcessManageSignal) XXX_Size() int {
	return xxx_messageInfo_ProcessManageSignal.Size(m)
}
func (m *ProcessManageSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessManageSignal.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessManageSignal proto.InternalMessageInfo

func (m *ProcessManageSignal) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ProcessManageSignal) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ProcessManageSignal) GetSignalType() string {
	if m != nil {
		return m.SignalType
	}
	return ""
}

func (m *ProcessManageSignal) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *ProcessManageSignal) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

func (m *ProcessManageSignal) GetChangeStrategy() string {
	if m != nil {
		return m.ChangeStrategy
	}
	return ""
}

func (m *ProcessManageSignal) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type StopCompleteRequest struct {
	JobId                string       `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Status               *Status      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,3,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StopCompleteRequest) Reset()         { *m = StopCompleteRequest{} }
func (m *StopCompleteRequest) String() string { return proto.CompactTextString(m) }
func (*StopCompleteRequest) ProtoMessage()    {}
func (*StopCompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{4}
}

func (m *StopCompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopCompleteRequest.Unmarshal(m, b)
}
func (m *StopCompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopCompleteRequest.Marshal(b, m, deterministic)
}
func (m *StopCompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopCompleteRequest.Merge(m, src)
}
func (m *StopCompleteRequest) XXX_Size() int {
	return xxx_messageInfo_StopCompleteRequest.Size(m)
}
func (m *StopCompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopCompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopCompleteRequest proto.InternalMessageInfo

func (m *StopCompleteRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *StopCompleteRequest) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StopCompleteRequest) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

type RecoverStrategyRequest struct {
	JobId                string       `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,2,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	Strategies           []string     `protobuf:"bytes,3,rep,name=strategies,proto3" json:"strategies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RecoverStrategyRequest) Reset()         { *m = RecoverStrategyRequest{} }
func (m *RecoverStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverStrategyRequest) ProtoMessage()    {}
func (*RecoverStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{5}
}

func (m *RecoverStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverStrategyRequest.Unmarshal(m, b)
}
func (m *RecoverStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverStrategyRequest.Marshal(b, m, deterministic)
}
func (m *RecoverStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverStrategyRequest.Merge(m, src)
}
func (m *RecoverStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverStrategyRequest.Size(m)
}
func (m *RecoverStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverStrategyRequest proto.InternalMessageInfo

func (m *RecoverStrategyRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RecoverStrategyRequest) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

func (m *RecoverStrategyRequest) GetStrategies() []string {
	if m != nil {
		return m.Strategies
	}
	return nil
}

type RecoverStatusRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Strategy             string   `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverStatusRequest) Reset()         { *m = RecoverStatusRequest{} }
func (m *RecoverStatusRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverStatusRequest) ProtoMessage()    {}
func (*RecoverStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{6}
}

func (m *RecoverStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverStatusRequest.Unmarshal(m, b)
}
func (m *RecoverStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverStatusRequest.Marshal(b, m, deterministic)
}
func (m *RecoverStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverStatusRequest.Merge(m, src)
}
func (m *RecoverStatusRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverStatusRequest.Size(m)
}
func (m *RecoverStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverStatusRequest proto.InternalMessageInfo

func (m *RecoverStatusRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RecoverStatusRequest) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RecoverStatusRequest) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

type ProcessFaultRequest struct {
	JobId                string       `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,2,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProcessFaultRequest) Reset()         { *m = ProcessFaultRequest{} }
func (m *ProcessFaultRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessFaultRequest) ProtoMessage()    {}
func (*ProcessFaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{7}
}

func (m *ProcessFaultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessFaultRequest.Unmarshal(m, b)
}
func (m *ProcessFaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessFaultRequest.Marshal(b, m, deterministic)
}
func (m *ProcessFaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessFaultRequest.Merge(m, src)
}
func (m *ProcessFaultRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessFaultRequest.Size(m)
}
func (m *ProcessFaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessFaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessFaultRequest proto.InternalMessageInfo

func (m *ProcessFaultRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ProcessFaultRequest) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

type SwitchNicResponse struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchNicResponse) Reset()         { *m = SwitchNicResponse{} }
func (m *SwitchNicResponse) String() string { return proto.CompactTextString(m) }
func (*SwitchNicResponse) ProtoMessage()    {}
func (*SwitchNicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{8}
}

func (m *SwitchNicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchNicResponse.Unmarshal(m, b)
}
func (m *SwitchNicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchNicResponse.Marshal(b, m, deterministic)
}
func (m *SwitchNicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchNicResponse.Merge(m, src)
}
func (m *SwitchNicResponse) XXX_Size() int {
	return xxx_messageInfo_SwitchNicResponse.Size(m)
}
func (m *SwitchNicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchNicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchNicResponse proto.InternalMessageInfo

func (m *SwitchNicResponse) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *SwitchNicResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SwitchNicRequest struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchNicRequest) Reset()         { *m = SwitchNicRequest{} }
func (m *SwitchNicRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchNicRequest) ProtoMessage()    {}
func (*SwitchNicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{9}
}

func (m *SwitchNicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchNicRequest.Unmarshal(m, b)
}
func (m *SwitchNicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchNicRequest.Marshal(b, m, deterministic)
}
func (m *SwitchNicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchNicRequest.Merge(m, src)
}
func (m *SwitchNicRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchNicRequest.Size(m)
}
func (m *SwitchNicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchNicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchNicRequest proto.InternalMessageInfo

func (m *SwitchNicRequest) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type SwitchNics struct {
	JobID                string                 `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	NicOps               map[string]*DeviceList `protobuf:"bytes,2,rep,name=nicOps,proto3" json:"nicOps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SwitchNics) Reset()         { *m = SwitchNics{} }
func (m *SwitchNics) String() string { return proto.CompactTextString(m) }
func (*SwitchNics) ProtoMessage()    {}
func (*SwitchNics) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{10}
}

func (m *SwitchNics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchNics.Unmarshal(m, b)
}
func (m *SwitchNics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchNics.Marshal(b, m, deterministic)
}
func (m *SwitchNics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchNics.Merge(m, src)
}
func (m *SwitchNics) XXX_Size() int {
	return xxx_messageInfo_SwitchNics.Size(m)
}
func (m *SwitchNics) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchNics.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchNics proto.InternalMessageInfo

func (m *SwitchNics) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *SwitchNics) GetNicOps() map[string]*DeviceList {
	if m != nil {
		return m.NicOps
	}
	return nil
}

type DeviceList struct {
	Dev                  []string `protobuf:"bytes,1,rep,name=dev,proto3" json:"dev,omitempty"`
	Op                   []bool   `protobuf:"varint,2,rep,packed,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceList) Reset()         { *m = DeviceList{} }
func (m *DeviceList) String() string { return proto.CompactTextString(m) }
func (*DeviceList) ProtoMessage()    {}
func (*DeviceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{11}
}

func (m *DeviceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceList.Unmarshal(m, b)
}
func (m *DeviceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceList.Marshal(b, m, deterministic)
}
func (m *DeviceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceList.Merge(m, src)
}
func (m *DeviceList) XXX_Size() int {
	return xxx_messageInfo_DeviceList.Size(m)
}
func (m *DeviceList) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceList.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceList proto.InternalMessageInfo

func (m *DeviceList) GetDev() []string {
	if m != nil {
		return m.Dev
	}
	return nil
}

func (m *DeviceList) GetOp() []bool {
	if m != nil {
		return m.Op
	}
	return nil
}

type SwitchRankList struct {
	RankID               []string `protobuf:"bytes,1,rep,name=rankID,proto3" json:"rankID,omitempty"`
	Op                   []bool   `protobuf:"varint,2,rep,packed,name=op,proto3" json:"op,omitempty"`
	JobId                string   `protobuf:"bytes,3,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchRankList) Reset()         { *m = SwitchRankList{} }
func (m *SwitchRankList) String() string { return proto.CompactTextString(m) }
func (*SwitchRankList) ProtoMessage()    {}
func (*SwitchRankList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{12}
}

func (m *SwitchRankList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchRankList.Unmarshal(m, b)
}
func (m *SwitchRankList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchRankList.Marshal(b, m, deterministic)
}
func (m *SwitchRankList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchRankList.Merge(m, src)
}
func (m *SwitchRankList) XXX_Size() int {
	return xxx_messageInfo_SwitchRankList.Size(m)
}
func (m *SwitchRankList) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchRankList.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchRankList proto.InternalMessageInfo

func (m *SwitchRankList) GetRankID() []string {
	if m != nil {
		return m.RankID
	}
	return nil
}

func (m *SwitchRankList) GetOp() []bool {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *SwitchRankList) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type SwitchResult struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchResult) Reset()         { *m = SwitchResult{} }
func (m *SwitchResult) String() string { return proto.CompactTextString(m) }
func (*SwitchResult) ProtoMessage()    {}
func (*SwitchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{13}
}

func (m *SwitchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchResult.Unmarshal(m, b)
}
func (m *SwitchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchResult.Marshal(b, m, deterministic)
}
func (m *SwitchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchResult.Merge(m, src)
}
func (m *SwitchResult) XXX_Size() int {
	return xxx_messageInfo_SwitchResult.Size(m)
}
func (m *SwitchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchResult proto.InternalMessageInfo

func (m *SwitchResult) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *SwitchResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type StressOpList struct {
	Ops                  []int64  `protobuf:"varint,2,rep,packed,name=ops,proto3" json:"ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StressOpList) Reset()         { *m = StressOpList{} }
func (m *StressOpList) String() string { return proto.CompactTextString(m) }
func (*StressOpList) ProtoMessage()    {}
func (*StressOpList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{14}
}

func (m *StressOpList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StressOpList.Unmarshal(m, b)
}
func (m *StressOpList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StressOpList.Marshal(b, m, deterministic)
}
func (m *StressOpList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StressOpList.Merge(m, src)
}
func (m *StressOpList) XXX_Size() int {
	return xxx_messageInfo_StressOpList.Size(m)
}
func (m *StressOpList) XXX_DiscardUnknown() {
	xxx_messageInfo_StressOpList.DiscardUnknown(m)
}

var xxx_messageInfo_StressOpList proto.InternalMessageInfo

func (m *StressOpList) GetOps() []int64 {
	if m != nil {
		return m.Ops
	}
	return nil
}

type StressTestParam struct {
	JobID                string                   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	StressParam          map[string]*StressOpList `protobuf:"bytes,2,rep,name=stressParam,proto3" json:"stressParam,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AllNodesOps          []int64                  `protobuf:"varint,3,rep,packed,name=allNodesOps,proto3" json:"allNodesOps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StressTestParam) Reset()         { *m = StressTestParam{} }
func (m *StressTestParam) String() string { return proto.CompactTextString(m) }
func (*StressTestParam) ProtoMessage()    {}
func (*StressTestParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{15}
}

func (m *StressTestParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StressTestParam.Unmarshal(m, b)
}
func (m *StressTestParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StressTestParam.Marshal(b, m, deterministic)
}
func (m *StressTestParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StressTestParam.Merge(m, src)
}
func (m *StressTestParam) XXX_Size() int {
	return xxx_messageInfo_StressTestParam.Size(m)
}
func (m *StressTestParam) XXX_DiscardUnknown() {
	xxx_messageInfo_StressTestParam.DiscardUnknown(m)
}

var xxx_messageInfo_StressTestParam proto.InternalMessageInfo

func (m *StressTestParam) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *StressTestParam) GetStressParam() map[string]*StressOpList {
	if m != nil {
		return m.StressParam
	}
	return nil
}

func (m *StressTestParam) GetAllNodesOps() []int64 {
	if m != nil {
		return m.AllNodesOps
	}
	return nil
}

type StressTestRequest struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StressTestRequest) Reset()         { *m = StressTestRequest{} }
func (m *StressTestRequest) String() string { return proto.CompactTextString(m) }
func (*StressTestRequest) ProtoMessage()    {}
func (*StressTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{16}
}

func (m *StressTestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StressTestRequest.Unmarshal(m, b)
}
func (m *StressTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StressTestRequest.Marshal(b, m, deterministic)
}
func (m *StressTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StressTestRequest.Merge(m, src)
}
func (m *StressTestRequest) XXX_Size() int {
	return xxx_messageInfo_StressTestRequest.Size(m)
}
func (m *StressTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StressTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StressTestRequest proto.InternalMessageInfo

func (m *StressTestRequest) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type StressTestResponse struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StressTestResponse) Reset()         { *m = StressTestResponse{} }
func (m *StressTestResponse) String() string { return proto.CompactTextString(m) }
func (*StressTestResponse) ProtoMessage()    {}
func (*StressTestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{17}
}

func (m *StressTestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StressTestResponse.Unmarshal(m, b)
}
func (m *StressTestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StressTestResponse.Marshal(b, m, deterministic)
}
func (m *StressTestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StressTestResponse.Merge(m, src)
}
func (m *StressTestResponse) XXX_Size() int {
	return xxx_messageInfo_StressTestResponse.Size(m)
}
func (m *StressTestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StressTestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StressTestResponse proto.InternalMessageInfo

func (m *StressTestResponse) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *StressTestResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StressTestRankParams struct {
	StressParam          map[string]*StressOpList `protobuf:"bytes,1,rep,name=stressParam,proto3" json:"stressParam,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	JobId                string                   `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StressTestRankParams) Reset()         { *m = StressTestRankParams{} }
func (m *StressTestRankParams) String() string { return proto.CompactTextString(m) }
func (*StressTestRankParams) ProtoMessage()    {}
func (*StressTestRankParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{18}
}

func (m *StressTestRankParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StressTestRankParams.Unmarshal(m, b)
}
func (m *StressTestRankParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StressTestRankParams.Marshal(b, m, deterministic)
}
func (m *StressTestRankParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StressTestRankParams.Merge(m, src)
}
func (m *StressTestRankParams) XXX_Size() int {
	return xxx_messageInfo_StressTestRankParams.Size(m)
}
func (m *StressTestRankParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StressTestRankParams.DiscardUnknown(m)
}

var xxx_messageInfo_StressTestRankParams proto.InternalMessageInfo

func (m *StressTestRankParams) GetStressParam() map[string]*StressOpList {
	if m != nil {
		return m.StressParam
	}
	return nil
}

func (m *StressTestRankParams) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type StressTestResult struct {
	JobId                string                           `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	StressResult         map[string]*StressTestRankResult `protobuf:"bytes,2,rep,name=stressResult,proto3" json:"stressResult,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *StressTestResult) Reset()         { *m = StressTestResult{} }
func (m *StressTestResult) String() string { return proto.CompactTextString(m) }
func (*StressTestResult) ProtoMessage()    {}
func (*StressTestResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{19}
}

func (m *StressTestResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StressTestResult.Unmarshal(m, b)
}
func (m *StressTestResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StressTestResult.Marshal(b, m, deterministic)
}
func (m *StressTestResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StressTestResult.Merge(m, src)
}
func (m *StressTestResult) XXX_Size() int {
	return xxx_messageInfo_StressTestResult.Size(m)
}
func (m *StressTestResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StressTestResult.DiscardUnknown(m)
}

var xxx_messageInfo_StressTestResult proto.InternalMessageInfo

func (m *StressTestResult) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *StressTestResult) GetStressResult() map[string]*StressTestRankResult {
	if m != nil {
		return m.StressResult
	}
	return nil
}

type StressTestRankResult struct {
	RankResult           map[string]*StressTestOpResult `protobuf:"bytes,1,rep,name=rankResult,proto3" json:"rankResult,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *StressTestRankResult) Reset()         { *m = StressTestRankResult{} }
func (m *StressTestRankResult) String() string { return proto.CompactTextString(m) }
func (*StressTestRankResult) ProtoMessage()    {}
func (*StressTestRankResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{20}
}

func (m *StressTestRankResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StressTestRankResult.Unmarshal(m, b)
}
func (m *StressTestRankResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StressTestRankResult.Marshal(b, m, deterministic)
}
func (m *StressTestRankResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StressTestRankResult.Merge(m, src)
}
func (m *StressTestRankResult) XXX_Size() int {
	return xxx_messageInfo_StressTestRankResult.Size(m)
}
func (m *StressTestRankResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StressTestRankResult.DiscardUnknown(m)
}

var xxx_messageInfo_StressTestRankResult proto.InternalMessageInfo

func (m *StressTestRankResult) GetRankResult() map[string]*StressTestOpResult {
	if m != nil {
		return m.RankResult
	}
	return nil
}

type StressTestOpResult struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StressTestOpResult) Reset()         { *m = StressTestOpResult{} }
func (m *StressTestOpResult) String() string { return proto.CompactTextString(m) }
func (*StressTestOpResult) ProtoMessage()    {}
func (*StressTestOpResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e825e73050144430, []int{21}
}

func (m *StressTestOpResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StressTestOpResult.Unmarshal(m, b)
}
func (m *StressTestOpResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StressTestOpResult.Marshal(b, m, deterministic)
}
func (m *StressTestOpResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StressTestOpResult.Merge(m, src)
}
func (m *StressTestOpResult) XXX_Size() int {
	return xxx_messageInfo_StressTestOpResult.Size(m)
}
func (m *StressTestOpResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StressTestOpResult.DiscardUnknown(m)
}

var xxx_messageInfo_StressTestOpResult proto.InternalMessageInfo

func (m *StressTestOpResult) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *StressTestOpResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*ClientInfo)(nil), "ClientInfo")
	proto.RegisterType((*FaultRank)(nil), "FaultRank")
	proto.RegisterType((*ProcessManageSignal)(nil), "ProcessManageSignal")
	proto.RegisterType((*StopCompleteRequest)(nil), "StopCompleteRequest")
	proto.RegisterType((*RecoverStrategyRequest)(nil), "RecoverStrategyRequest")
	proto.RegisterType((*RecoverStatusRequest)(nil), "RecoverStatusRequest")
	proto.RegisterType((*ProcessFaultRequest)(nil), "ProcessFaultRequest")
	proto.RegisterType((*SwitchNicResponse)(nil), "SwitchNicResponse")
	proto.RegisterType((*SwitchNicRequest)(nil), "SwitchNicRequest")
	proto.RegisterType((*SwitchNics)(nil), "SwitchNics")
	proto.RegisterMapType((map[string]*DeviceList)(nil), "SwitchNics.NicOpsEntry")
	proto.RegisterType((*DeviceList)(nil), "DeviceList")
	proto.RegisterType((*SwitchRankList)(nil), "SwitchRankList")
	proto.RegisterType((*SwitchResult)(nil), "SwitchResult")
	proto.RegisterType((*StressOpList)(nil), "StressOpList")
	proto.RegisterType((*StressTestParam)(nil), "StressTestParam")
	proto.RegisterMapType((map[string]*StressOpList)(nil), "StressTestParam.StressParamEntry")
	proto.RegisterType((*StressTestRequest)(nil), "StressTestRequest")
	proto.RegisterType((*StressTestResponse)(nil), "StressTestResponse")
	proto.RegisterType((*StressTestRankParams)(nil), "StressTestRankParams")
	proto.RegisterMapType((map[string]*StressOpList)(nil), "StressTestRankParams.StressParamEntry")
	proto.RegisterType((*StressTestResult)(nil), "StressTestResult")
	proto.RegisterMapType((map[string]*StressTestRankResult)(nil), "StressTestResult.StressResultEntry")
	proto.RegisterType((*StressTestRankResult)(nil), "StressTestRankResult")
	proto.RegisterMapType((map[string]*StressTestOpResult)(nil), "StressTestRankResult.RankResultEntry")
	proto.RegisterType((*StressTestOpResult)(nil), "StressTestOpResult")
}

func init() {
	proto.RegisterFile("recover.proto", fileDescriptor_e825e73050144430)
}

var fileDescriptor_e825e73050144430 = []byte{
	// 1074 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x72, 0x1b, 0x35,
	0x14, 0xee, 0xda, 0x89, 0x13, 0x1f, 0x37, 0x7f, 0x4a, 0xdc, 0x7a, 0x4c, 0x29, 0xee, 0x76, 0xda,
	0x71, 0x60, 0x46, 0x64, 0xc2, 0xf0, 0x9b, 0x5e, 0x00, 0x49, 0xda, 0x86, 0xa1, 0x4e, 0x47, 0xce,
	0xc0, 0x0c, 0x77, 0xeb, 0x8d, 0xec, 0x2c, 0xde, 0xac, 0x96, 0x95, 0x1c, 0x6a, 0x5e, 0x85, 0xa7,
	0xe0, 0x21, 0xb8, 0xe0, 0x21, 0xb8, 0xe6, 0x05, 0x78, 0x00, 0x46, 0x5a, 0x69, 0x57, 0xbb, 0x5e,
	0x87, 0x61, 0xe8, 0x9d, 0xa4, 0x3d, 0xdf, 0x39, 0xdf, 0xf9, 0xce, 0xb1, 0x8e, 0x0c, 0x1b, 0x09,
	0xf5, 0xd9, 0x0d, 0x4d, 0x70, 0x9c, 0x30, 0xc1, 0xdc, 0x03, 0x68, 0x0c, 0x85, 0x27, 0x66, 0x1c,
	0x21, 0x58, 0xf1, 0xd9, 0x25, 0xed, 0x38, 0x3d, 0xa7, 0xbf, 0x4a, 0xd4, 0x5a, 0x9e, 0x05, 0xd1,
	0x98, 0x75, 0x6a, 0x3d, 0xa7, 0xdf, 0x24, 0x6a, 0xed, 0x7e, 0x02, 0x70, 0x1c, 0x06, 0x34, 0x12,
	0x67, 0xd1, 0x98, 0xa1, 0x3d, 0x58, 0xfd, 0x91, 0x8d, 0xce, 0x2e, 0x15, 0xac, 0x49, 0xd2, 0x8d,
	0xc4, 0x25, 0x2c, 0xa4, 0x06, 0x27, 0xd7, 0xee, 0x57, 0xd0, 0x7c, 0xee, 0xcd, 0x42, 0x41, 0xbc,
	0x68, 0x8a, 0xee, 0x41, 0x23, 0xf1, 0xa2, 0x69, 0x86, 0xd3, 0x3b, 0xf4, 0x00, 0x9a, 0x63, 0x69,
	0x74, 0x31, 0x8f, 0x0d, 0x3a, 0x3f, 0x70, 0xff, 0x72, 0x60, 0xf7, 0x75, 0xc2, 0x7c, 0xca, 0xf9,
	0x2b, 0x2f, 0xf2, 0x26, 0x74, 0x18, 0x4c, 0x22, 0x2f, 0x94, 0xe1, 0x66, 0xb3, 0xc0, 0xf8, 0x52,
	0xeb, 0x9c, 0x58, 0xcd, 0x26, 0xf6, 0x10, 0x80, 0x2b, 0x8c, 0x0a, 0x50, 0x57, 0x9f, 0xac, 0x13,
	0xd4, 0x81, 0x35, 0xcf, 0x17, 0x01, 0x8b, 0x78, 0x67, 0xa5, 0x57, 0xef, 0x37, 0x89, 0xd9, 0xa2,
	0xf7, 0x01, 0xc6, 0x86, 0x3e, 0xef, 0xac, 0xf6, 0xea, 0xfd, 0xd6, 0x21, 0xe0, 0x2c, 0x23, 0x62,
	0x7d, 0x45, 0x4f, 0x61, 0xd3, 0xbf, 0xf2, 0xa2, 0x09, 0x1d, 0x8a, 0xc4, 0x13, 0x74, 0x32, 0xef,
	0x34, 0x54, 0xa4, 0xd2, 0xa9, 0x8c, 0x26, 0x82, 0x6b, 0xca, 0x66, 0xa2, 0xb3, 0xd6, 0x73, 0xfa,
	0x75, 0x62, 0xb6, 0xee, 0x1b, 0xd8, 0x1d, 0x0a, 0x16, 0x1f, 0xb3, 0xeb, 0x38, 0xa4, 0x82, 0x12,
	0xfa, 0xd3, 0x8c, 0x72, 0xb1, 0x44, 0xed, 0xf7, 0xa0, 0xc1, 0x55, 0x0d, 0x55, 0xae, 0xad, 0xc3,
	0x35, 0x9c, 0x96, 0x94, 0xe8, 0xe3, 0x12, 0xf7, 0xfa, 0x6d, 0xdc, 0xdd, 0x5f, 0xe0, 0x1e, 0x49,
	0x3b, 0xc4, 0xd0, 0xbc, 0x3d, 0x78, 0xd1, 0x77, 0xed, 0x56, 0x5d, 0xa4, 0xfa, 0xa9, 0xd3, 0x80,
	0xa6, 0x3c, 0xa4, 0xfa, 0xd9, 0x89, 0x1b, 0xc0, 0x5e, 0x16, 0x5b, 0x25, 0xf0, 0xff, 0xd2, 0xee,
	0xc2, 0x3a, 0x37, 0x05, 0x48, 0x4b, 0x9d, 0xed, 0xdd, 0xef, 0xb3, 0x4e, 0x4a, 0xa9, 0xbe, 0xad,
	0x1c, 0xdd, 0x23, 0xd8, 0x19, 0xfe, 0x1c, 0x08, 0xff, 0x6a, 0x10, 0xf8, 0x84, 0xf2, 0x98, 0x45,
	0x9c, 0x1a, 0xb7, 0x27, 0xb6, 0xdb, 0x13, 0xb4, 0x0d, 0xf5, 0x6b, 0x3e, 0xd1, 0x0d, 0x2a, 0x97,
	0x6e, 0x1f, 0xb6, 0x2d, 0x70, 0x81, 0x52, 0x11, 0xeb, 0xfe, 0xea, 0x00, 0x64, 0xa6, 0x7c, 0x49,
	0x80, 0x0f, 0xa1, 0x11, 0x05, 0xfe, 0x79, 0x6c, 0x38, 0xdf, 0xc7, 0x39, 0x04, 0x0f, 0xd4, 0x97,
	0xd3, 0x48, 0x24, 0x73, 0xa2, 0xcd, 0xba, 0xcf, 0xa1, 0x65, 0x1d, 0x4b, 0x82, 0x53, 0x3a, 0xd7,
	0x3e, 0xe5, 0x12, 0x3d, 0x82, 0xd5, 0x1b, 0x2f, 0x9c, 0x51, 0x2d, 0x79, 0x0b, 0x9f, 0xd0, 0x9b,
	0xc0, 0xa7, 0xdf, 0x06, 0x5c, 0x90, 0xf4, 0xcb, 0x17, 0xb5, 0xcf, 0x1c, 0x17, 0x03, 0xe4, 0x1f,
	0xa4, 0x9b, 0x4b, 0x7a, 0xd3, 0x71, 0x54, 0xbd, 0xe5, 0x12, 0x6d, 0x42, 0x8d, 0xc5, 0x8a, 0xd4,
	0x3a, 0xa9, 0xb1, 0xd8, 0x1d, 0xc0, 0x66, 0xca, 0x4c, 0x6a, 0xa8, 0x30, 0xe6, 0x82, 0x38, 0xd1,
	0x30, 0xbd, 0x2b, 0x23, 0xf3, 0x82, 0xd5, 0xad, 0x82, 0xb9, 0xcf, 0xe0, 0xae, 0xf6, 0x47, 0xf9,
	0x2c, 0x5c, 0x56, 0x56, 0x19, 0x43, 0x7d, 0x57, 0xd9, 0xac, 0x13, 0xbd, 0x73, 0x7b, 0x70, 0x77,
	0x28, 0x12, 0xca, 0xf9, 0x79, 0x6c, 0xf8, 0x33, 0xad, 0x61, 0x9d, 0xc8, 0xa5, 0xfb, 0xa7, 0x03,
	0x5b, 0xa9, 0xc9, 0x05, 0xe5, 0xe2, 0xb5, 0x97, 0x78, 0xd7, 0x4b, 0x4a, 0x70, 0x0c, 0x2d, 0xae,
	0x0c, 0x95, 0x91, 0xae, 0xc3, 0x23, 0x5c, 0x02, 0xeb, 0xbd, 0x5a, 0xa7, 0x15, 0xb1, 0x51, 0xa8,
	0x07, 0x2d, 0x2f, 0x0c, 0x07, 0xec, 0x92, 0x72, 0x59, 0xcc, 0xba, 0x22, 0x62, 0x1f, 0x75, 0x5f,
	0xc1, 0x76, 0xd9, 0x45, 0x45, 0xf5, 0x1e, 0x17, 0xab, 0xb7, 0x81, 0xed, 0x34, 0xed, 0xfa, 0xed,
	0xc3, 0x4e, 0xce, 0xf0, 0xf6, 0x46, 0x7c, 0x06, 0xc8, 0x36, 0xfd, 0x8f, 0x0d, 0xff, 0xbb, 0x03,
	0x7b, 0x16, 0xdc, 0x8b, 0xa6, 0x2a, 0x01, 0x8e, 0x5e, 0x16, 0x75, 0x73, 0x94, 0x6e, 0x4f, 0x71,
	0x95, 0xed, 0xbf, 0x88, 0x57, 0x39, 0x08, 0xde, 0xb6, 0x60, 0x7f, 0x38, 0xc6, 0x9f, 0x96, 0x61,
	0x79, 0xd7, 0xbd, 0x80, 0xbb, 0x29, 0x3d, 0x62, 0x7a, 0x4f, 0xa6, 0xf6, 0x18, 0x97, 0xe1, 0xfa,
	0x20, 0xdd, 0xa4, 0x79, 0x15, 0x80, 0xdd, 0xef, 0x4c, 0x91, 0x2c, 0x93, 0x8a, 0x1c, 0x3e, 0x28,
	0xe6, 0xd0, 0x2e, 0x69, 0x98, 0x82, 0xed, 0x5c, 0x7e, 0x5b, 0xa8, 0x89, 0xce, 0xe7, 0x14, 0x20,
	0xc9, 0x76, 0xba, 0x24, 0x4f, 0x2a, 0xdd, 0xe1, 0x7c, 0x99, 0x32, 0xb7, 0x80, 0x5d, 0x02, 0x5b,
	0xa5, 0xcf, 0x15, 0xac, 0xf7, 0x8b, 0xac, 0x77, 0xad, 0x30, 0xe7, 0xf1, 0x22, 0xe7, 0x2f, 0xed,
	0x2e, 0x34, 0x06, 0x85, 0x27, 0x4d, 0x53, 0x3f, 0x69, 0x8a, 0x3f, 0xfa, 0xa6, 0xf9, 0xd1, 0x1f,
	0xfe, 0xdd, 0x80, 0x35, 0x3d, 0x7c, 0xd0, 0x43, 0x58, 0x39, 0x8b, 0x02, 0x81, 0x5a, 0x38, 0x7f,
	0xe9, 0x74, 0xcd, 0x78, 0x71, 0xef, 0x20, 0x17, 0xd6, 0x09, 0x9d, 0x04, 0x5c, 0xd0, 0x64, 0xa9,
	0xcd, 0x29, 0x3c, 0x18, 0xce, 0x46, 0xdc, 0x4f, 0x82, 0x11, 0xad, 0x7a, 0xb3, 0x14, 0x70, 0x7b,
	0xb8, 0xc2, 0xc4, 0xbd, 0x73, 0xe0, 0xa0, 0x8f, 0x01, 0x11, 0x1a, 0xb3, 0x44, 0xd8, 0xcf, 0x01,
	0xb4, 0x87, 0x2b, 0x5e, 0x07, 0x76, 0xf4, 0x23, 0x68, 0xa7, 0xb0, 0xd2, 0x2c, 0x47, 0xf7, 0x71,
	0xf5, 0x74, 0xb7, 0xc1, 0x9f, 0xc2, 0x6e, 0x09, 0xac, 0xc6, 0x69, 0x1b, 0x57, 0x0d, 0x67, 0x1b,
	0x98, 0x91, 0xb5, 0x47, 0x2b, 0xca, 0x92, 0xb3, 0x27, 0xad, 0x0d, 0xeb, 0x9b, 0xdb, 0x7f, 0x10,
	0xf8, 0x17, 0x89, 0xe7, 0x4f, 0x51, 0xcb, 0x1a, 0x54, 0x45, 0x51, 0x3b, 0x99, 0xa8, 0x99, 0x85,
	0x16, 0x74, 0x07, 0x97, 0x47, 0x67, 0x17, 0xe1, 0x85, 0x51, 0xac, 0x44, 0xfd, 0x1c, 0xda, 0x99,
	0x9b, 0x01, 0x13, 0xc1, 0x78, 0x9e, 0xda, 0x15, 0x8b, 0xb2, 0x85, 0x8b, 0x33, 0x49, 0x41, 0x0f,
	0xe4, 0x13, 0x25, 0x0e, 0xe7, 0xb6, 0x63, 0x99, 0xe4, 0x06, 0xb6, 0x07, 0x8e, 0xcd, 0xf9, 0x09,
	0xb4, 0x5e, 0x52, 0x2f, 0x14, 0x57, 0xc7, 0x57, 0x54, 0xa5, 0x56, 0xdd, 0x2f, 0xfb, 0x00, 0x79,
	0x07, 0xa3, 0xed, 0xf2, 0x84, 0xb0, 0x4d, 0xbf, 0x81, 0x77, 0x72, 0x15, 0x16, 0xef, 0x5e, 0x84,
	0x17, 0xee, 0xee, 0xee, 0x2e, 0x5e, 0x34, 0x54, 0xf9, 0xbc, 0x80, 0x77, 0x4b, 0x52, 0x9c, 0xbe,
	0xa1, 0xbe, 0xc5, 0xa4, 0xc0, 0xb7, 0x5d, 0x79, 0x01, 0xeb, 0x46, 0x6d, 0xa7, 0xc2, 0x94, 0x6f,
	0xc1, 0x9d, 0x85, 0x9b, 0xcd, 0xca, 0xe5, 0xeb, 0xc6, 0x0f, 0x2b, 0xf8, 0x28, 0x1e, 0x8d, 0x1a,
	0xea, 0xef, 0xc8, 0x47, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x97, 0xe0, 0xef, 0xbb, 0x9f, 0x0c,
	0x00, 0x00,
}
