// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: recover.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Recover_Init_FullMethodName                         = "/Recover/Init"
	Recover_Register_FullMethodName                     = "/Recover/Register"
	Recover_SubscribeProcessManageSignal_FullMethodName = "/Recover/SubscribeProcessManageSignal"
	Recover_ReportStopComplete_FullMethodName           = "/Recover/ReportStopComplete"
	Recover_ReportRecoverStrategy_FullMethodName        = "/Recover/ReportRecoverStrategy"
	Recover_ReportRecoverStatus_FullMethodName          = "/Recover/ReportRecoverStatus"
	Recover_ReportProcessFault_FullMethodName           = "/Recover/ReportProcessFault"
	Recover_SwitchNicTrack_FullMethodName               = "/Recover/SwitchNicTrack"
	Recover_SubscribeSwitchNicSignal_FullMethodName     = "/Recover/SubscribeSwitchNicSignal"
	Recover_SubscribeNotifySwitch_FullMethodName        = "/Recover/SubscribeNotifySwitch"
	Recover_ReplySwitchNicResult_FullMethodName         = "/Recover/ReplySwitchNicResult"
)

// RecoverClient is the client API for Recover service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecoverClient interface {
	Init(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error)
	Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error)
	SubscribeProcessManageSignal(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Recover_SubscribeProcessManageSignalClient, error)
	ReportStopComplete(ctx context.Context, in *StopCompleteRequest, opts ...grpc.CallOption) (*Status, error)
	ReportRecoverStrategy(ctx context.Context, in *RecoverStrategyRequest, opts ...grpc.CallOption) (*Status, error)
	ReportRecoverStatus(ctx context.Context, in *RecoverStatusRequest, opts ...grpc.CallOption) (*Status, error)
	ReportProcessFault(ctx context.Context, in *ProcessFaultRequest, opts ...grpc.CallOption) (*Status, error)
	SwitchNicTrack(ctx context.Context, in *SwitchNics, opts ...grpc.CallOption) (*Status, error)
	SubscribeSwitchNicSignal(ctx context.Context, in *SwitchNicRequest, opts ...grpc.CallOption) (Recover_SubscribeSwitchNicSignalClient, error)
	SubscribeNotifySwitch(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Recover_SubscribeNotifySwitchClient, error)
	ReplySwitchNicResult(ctx context.Context, in *SwitchResult, opts ...grpc.CallOption) (*Status, error)
}

type recoverClient struct {
	cc grpc.ClientConnInterface
}

func NewRecoverClient(cc grpc.ClientConnInterface) RecoverClient {
	return &recoverClient{cc}
}

func (c *recoverClient) Init(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_Init_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) SubscribeProcessManageSignal(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Recover_SubscribeProcessManageSignalClient, error) {
	stream, err := c.cc.NewStream(ctx, &Recover_ServiceDesc.Streams[0], Recover_SubscribeProcessManageSignal_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &recoverSubscribeProcessManageSignalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Recover_SubscribeProcessManageSignalClient interface {
	Recv() (*ProcessManageSignal, error)
	grpc.ClientStream
}

type recoverSubscribeProcessManageSignalClient struct {
	grpc.ClientStream
}

func (x *recoverSubscribeProcessManageSignalClient) Recv() (*ProcessManageSignal, error) {
	m := new(ProcessManageSignal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recoverClient) ReportStopComplete(ctx context.Context, in *StopCompleteRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_ReportStopComplete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) ReportRecoverStrategy(ctx context.Context, in *RecoverStrategyRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_ReportRecoverStrategy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) ReportRecoverStatus(ctx context.Context, in *RecoverStatusRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_ReportRecoverStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) ReportProcessFault(ctx context.Context, in *ProcessFaultRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_ReportProcessFault_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) SwitchNicTrack(ctx context.Context, in *SwitchNics, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_SwitchNicTrack_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) SubscribeSwitchNicSignal(ctx context.Context, in *SwitchNicRequest, opts ...grpc.CallOption) (Recover_SubscribeSwitchNicSignalClient, error) {
	stream, err := c.cc.NewStream(ctx, &Recover_ServiceDesc.Streams[1], Recover_SubscribeSwitchNicSignal_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &recoverSubscribeSwitchNicSignalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Recover_SubscribeSwitchNicSignalClient interface {
	Recv() (*SwitchNicResponse, error)
	grpc.ClientStream
}

type recoverSubscribeSwitchNicSignalClient struct {
	grpc.ClientStream
}

func (x *recoverSubscribeSwitchNicSignalClient) Recv() (*SwitchNicResponse, error) {
	m := new(SwitchNicResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recoverClient) SubscribeNotifySwitch(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Recover_SubscribeNotifySwitchClient, error) {
	stream, err := c.cc.NewStream(ctx, &Recover_ServiceDesc.Streams[2], Recover_SubscribeNotifySwitch_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &recoverSubscribeNotifySwitchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Recover_SubscribeNotifySwitchClient interface {
	Recv() (*SwitchRankList, error)
	grpc.ClientStream
}

type recoverSubscribeNotifySwitchClient struct {
	grpc.ClientStream
}

func (x *recoverSubscribeNotifySwitchClient) Recv() (*SwitchRankList, error) {
	m := new(SwitchRankList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recoverClient) ReplySwitchNicResult(ctx context.Context, in *SwitchResult, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_ReplySwitchNicResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecoverServer is the server API for Recover service.
// All implementations must embed UnimplementedRecoverServer
// for forward compatibility
type RecoverServer interface {
	Init(context.Context, *ClientInfo) (*Status, error)
	Register(context.Context, *ClientInfo) (*Status, error)
	SubscribeProcessManageSignal(*ClientInfo, Recover_SubscribeProcessManageSignalServer) error
	ReportStopComplete(context.Context, *StopCompleteRequest) (*Status, error)
	ReportRecoverStrategy(context.Context, *RecoverStrategyRequest) (*Status, error)
	ReportRecoverStatus(context.Context, *RecoverStatusRequest) (*Status, error)
	ReportProcessFault(context.Context, *ProcessFaultRequest) (*Status, error)
	SwitchNicTrack(context.Context, *SwitchNics) (*Status, error)
	SubscribeSwitchNicSignal(*SwitchNicRequest, Recover_SubscribeSwitchNicSignalServer) error
	SubscribeNotifySwitch(*ClientInfo, Recover_SubscribeNotifySwitchServer) error
	ReplySwitchNicResult(context.Context, *SwitchResult) (*Status, error)
	mustEmbedUnimplementedRecoverServer()
}

// UnimplementedRecoverServer must be embedded to have forward compatible implementations.
type UnimplementedRecoverServer struct {
}

func (UnimplementedRecoverServer) Init(context.Context, *ClientInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedRecoverServer) Register(context.Context, *ClientInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRecoverServer) SubscribeProcessManageSignal(*ClientInfo, Recover_SubscribeProcessManageSignalServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeProcessManageSignal not implemented")
}
func (UnimplementedRecoverServer) ReportStopComplete(context.Context, *StopCompleteRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStopComplete not implemented")
}
func (UnimplementedRecoverServer) ReportRecoverStrategy(context.Context, *RecoverStrategyRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportRecoverStrategy not implemented")
}
func (UnimplementedRecoverServer) ReportRecoverStatus(context.Context, *RecoverStatusRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportRecoverStatus not implemented")
}
func (UnimplementedRecoverServer) ReportProcessFault(context.Context, *ProcessFaultRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportProcessFault not implemented")
}
func (UnimplementedRecoverServer) SwitchNicTrack(context.Context, *SwitchNics) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchNicTrack not implemented")
}
func (UnimplementedRecoverServer) SubscribeSwitchNicSignal(*SwitchNicRequest, Recover_SubscribeSwitchNicSignalServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeSwitchNicSignal not implemented")
}
func (UnimplementedRecoverServer) SubscribeNotifySwitch(*ClientInfo, Recover_SubscribeNotifySwitchServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeNotifySwitch not implemented")
}
func (UnimplementedRecoverServer) ReplySwitchNicResult(context.Context, *SwitchResult) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplySwitchNicResult not implemented")
}
func (UnimplementedRecoverServer) mustEmbedUnimplementedRecoverServer() {}

// UnsafeRecoverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecoverServer will
// result in compilation errors.
type UnsafeRecoverServer interface {
	mustEmbedUnimplementedRecoverServer()
}

func RegisterRecoverServer(s grpc.ServiceRegistrar, srv RecoverServer) {
	s.RegisterService(&Recover_ServiceDesc, srv)
}

func _Recover_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).Init(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).Register(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_SubscribeProcessManageSignal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecoverServer).SubscribeProcessManageSignal(m, &recoverSubscribeProcessManageSignalServer{stream})
}

type Recover_SubscribeProcessManageSignalServer interface {
	Send(*ProcessManageSignal) error
	grpc.ServerStream
}

type recoverSubscribeProcessManageSignalServer struct {
	grpc.ServerStream
}

func (x *recoverSubscribeProcessManageSignalServer) Send(m *ProcessManageSignal) error {
	return x.ServerStream.SendMsg(m)
}

func _Recover_ReportStopComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).ReportStopComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_ReportStopComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).ReportStopComplete(ctx, req.(*StopCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_ReportRecoverStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).ReportRecoverStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_ReportRecoverStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).ReportRecoverStrategy(ctx, req.(*RecoverStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_ReportRecoverStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).ReportRecoverStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_ReportRecoverStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).ReportRecoverStatus(ctx, req.(*RecoverStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_ReportProcessFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).ReportProcessFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_ReportProcessFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).ReportProcessFault(ctx, req.(*ProcessFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_SwitchNicTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchNics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).SwitchNicTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_SwitchNicTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).SwitchNicTrack(ctx, req.(*SwitchNics))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_SubscribeSwitchNicSignal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SwitchNicRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecoverServer).SubscribeSwitchNicSignal(m, &recoverSubscribeSwitchNicSignalServer{stream})
}

type Recover_SubscribeSwitchNicSignalServer interface {
	Send(*SwitchNicResponse) error
	grpc.ServerStream
}

type recoverSubscribeSwitchNicSignalServer struct {
	grpc.ServerStream
}

func (x *recoverSubscribeSwitchNicSignalServer) Send(m *SwitchNicResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Recover_SubscribeNotifySwitch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecoverServer).SubscribeNotifySwitch(m, &recoverSubscribeNotifySwitchServer{stream})
}

type Recover_SubscribeNotifySwitchServer interface {
	Send(*SwitchRankList) error
	grpc.ServerStream
}

type recoverSubscribeNotifySwitchServer struct {
	grpc.ServerStream
}

func (x *recoverSubscribeNotifySwitchServer) Send(m *SwitchRankList) error {
	return x.ServerStream.SendMsg(m)
}

func _Recover_ReplySwitchNicResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).ReplySwitchNicResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_ReplySwitchNicResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).ReplySwitchNicResult(ctx, req.(*SwitchResult))
	}
	return interceptor(ctx, in, info, handler)
}

// Recover_ServiceDesc is the grpc.ServiceDesc for Recover service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recover_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Recover",
	HandlerType: (*RecoverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Recover_Init_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Recover_Register_Handler,
		},
		{
			MethodName: "ReportStopComplete",
			Handler:    _Recover_ReportStopComplete_Handler,
		},
		{
			MethodName: "ReportRecoverStrategy",
			Handler:    _Recover_ReportRecoverStrategy_Handler,
		},
		{
			MethodName: "ReportRecoverStatus",
			Handler:    _Recover_ReportRecoverStatus_Handler,
		},
		{
			MethodName: "ReportProcessFault",
			Handler:    _Recover_ReportProcessFault_Handler,
		},
		{
			MethodName: "SwitchNicTrack",
			Handler:    _Recover_SwitchNicTrack_Handler,
		},
		{
			MethodName: "ReplySwitchNicResult",
			Handler:    _Recover_ReplySwitchNicResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeProcessManageSignal",
			Handler:       _Recover_SubscribeProcessManageSignal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeSwitchNicSignal",
			Handler:       _Recover_SubscribeSwitchNicSignal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeNotifySwitch",
			Handler:       _Recover_SubscribeNotifySwitch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "recover.proto",
}
