# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recover.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrecover.proto\"$\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04info\x18\x02 \x01(\t\")\n\nClientInfo\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\".\n\tFaultRank\x12\x0e\n\x06rankId\x18\x01 \x01(\t\x12\x11\n\tfaultType\x18\x02 \x01(\t\"\x8f\x01\n\x13ProcessManageSignal\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05jobId\x18\x02 \x01(\t\x12\x12\n\nsignalType\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x63tions\x18\x04 \x03(\t\x12\x1e\n\nfaultRanks\x18\x05 \x03(\x0b\x32\n.FaultRank\x12\x16\n\x0e\x63hangeStrategy\x18\x06 \x01(\t\"]\n\x13StopCompleteRequest\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x17\n\x06status\x18\x02 \x01(\x0b\x32\x07.Status\x12\x1e\n\nfaultRanks\x18\x03 \x03(\x0b\x32\n.FaultRank\"[\n\x16RecoverStrategyRequest\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x1e\n\nfaultRanks\x18\x02 \x03(\x0b\x32\n.FaultRank\x12\x12\n\nstrategies\x18\x03 \x03(\t\"P\n\x14RecoverStatusRequest\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x17\n\x06status\x18\x02 \x01(\x0b\x32\x07.Status\x12\x10\n\x08strategy\x18\x03 \x01(\t\"D\n\x13ProcessFaultRequest\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x1e\n\nfaultRanks\x18\x02 \x03(\x0b\x32\n.FaultRank2\xf8\x02\n\x07Recover\x12\x1e\n\x04Init\x12\x0b.ClientInfo\x1a\x07.Status\"\x00\x12\"\n\x08Register\x12\x0b.ClientInfo\x1a\x07.Status\"\x00\x12\x45\n\x1cSubscribeProcessManageSignal\x12\x0b.ClientInfo\x1a\x14.ProcessManageSignal\"\x00\x30\x01\x12\x35\n\x12ReportStopComplete\x12\x14.StopCompleteRequest\x1a\x07.Status\"\x00\x12;\n\x15ReportRecoverStrategy\x12\x17.RecoverStrategyRequest\x1a\x07.Status\"\x00\x12\x37\n\x13ReportRecoverStatus\x12\x15.RecoverStatusRequest\x1a\x07.Status\"\x00\x12\x35\n\x12ReportProcessFault\x12\x14.ProcessFaultRequest\x1a\x07.Status\"\x00\x42\x06Z\x04.;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recover_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    _globals['DESCRIPTOR']._options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\004.;pb'
    _globals['_STATUS']._serialized_start = 17
    _globals['_STATUS']._serialized_end = 53
    _globals['_CLIENTINFO']._serialized_start = 55
    _globals['_CLIENTINFO']._serialized_end = 96
    _globals['_FAULTRANK']._serialized_start = 98
    _globals['_FAULTRANK']._serialized_end = 144
    _globals['_PROCESSMANAGESIGNAL']._serialized_start = 147
    _globals['_PROCESSMANAGESIGNAL']._serialized_end = 290
    _globals['_STOPCOMPLETEREQUEST']._serialized_start = 292
    _globals['_STOPCOMPLETEREQUEST']._serialized_end = 385
    _globals['_RECOVERSTRATEGYREQUEST']._serialized_start = 387
    _globals['_RECOVERSTRATEGYREQUEST']._serialized_end = 478
    _globals['_RECOVERSTATUSREQUEST']._serialized_start = 480
    _globals['_RECOVERSTATUSREQUEST']._serialized_end = 560
    _globals['_PROCESSFAULTREQUEST']._serialized_start = 562
    _globals['_PROCESSFAULTREQUEST']._serialized_end = 630
    _globals['_RECOVER']._serialized_start = 633
    _globals['_RECOVER']._serialized_end = 1009
# @@protoc_insertion_point(module_scope)
