# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import recover_pb2 as recover__pb2


class RecoverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/Recover/Init',
                request_serializer=recover__pb2.ClientInfo.SerializeToString,
                response_deserializer=recover__pb2.Status.FromString,
                )
        self.Register = channel.unary_unary(
                '/Recover/Register',
                request_serializer=recover__pb2.ClientInfo.SerializeToString,
                response_deserializer=recover__pb2.Status.FromString,
                )
        self.SubscribeProcessManageSignal = channel.unary_stream(
                '/Recover/SubscribeProcessManageSignal',
                request_serializer=recover__pb2.ClientInfo.SerializeToString,
                response_deserializer=recover__pb2.ProcessManageSignal.FromString,
                )
        self.ReportStopComplete = channel.unary_unary(
                '/Recover/ReportStopComplete',
                request_serializer=recover__pb2.StopCompleteRequest.SerializeToString,
                response_deserializer=recover__pb2.Status.FromString,
                )
        self.ReportRecoverStrategy = channel.unary_unary(
                '/Recover/ReportRecoverStrategy',
                request_serializer=recover__pb2.RecoverStrategyRequest.SerializeToString,
                response_deserializer=recover__pb2.Status.FromString,
                )
        self.ReportRecoverStatus = channel.unary_unary(
                '/Recover/ReportRecoverStatus',
                request_serializer=recover__pb2.RecoverStatusRequest.SerializeToString,
                response_deserializer=recover__pb2.Status.FromString,
                )
        self.ReportProcessFault = channel.unary_unary(
                '/Recover/ReportProcessFault',
                request_serializer=recover__pb2.ProcessFaultRequest.SerializeToString,
                response_deserializer=recover__pb2.Status.FromString,
                )
        self.SwitchNicTrack = channel.unary_unary(
                '/Recover/SwitchNicTrack',
                request_serializer=recover__pb2.SwitchNics.SerializeToString,
                response_deserializer=recover__pb2.Status.FromString,
                )
        self.SubscribeSwitchNicSignal = channel.unary_stream(
                '/Recover/SubscribeSwitchNicSignal',
                request_serializer=recover__pb2.SwitchNicRequest.SerializeToString,
                response_deserializer=recover__pb2.SwitchNicResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/Recover/HealthCheck',
                request_serializer=recover__pb2.ClientInfo.SerializeToString,
                response_deserializer=recover__pb2.Status.FromString,
                )


class RecoverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeProcessManageSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStopComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportRecoverStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportRecoverStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportProcessFault(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchNicTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeSwitchNicSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecoverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=recover__pb2.ClientInfo.FromString,
                    response_serializer=recover__pb2.Status.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=recover__pb2.ClientInfo.FromString,
                    response_serializer=recover__pb2.Status.SerializeToString,
            ),
            'SubscribeProcessManageSignal': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeProcessManageSignal,
                    request_deserializer=recover__pb2.ClientInfo.FromString,
                    response_serializer=recover__pb2.ProcessManageSignal.SerializeToString,
            ),
            'ReportStopComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStopComplete,
                    request_deserializer=recover__pb2.StopCompleteRequest.FromString,
                    response_serializer=recover__pb2.Status.SerializeToString,
            ),
            'ReportRecoverStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportRecoverStrategy,
                    request_deserializer=recover__pb2.RecoverStrategyRequest.FromString,
                    response_serializer=recover__pb2.Status.SerializeToString,
            ),
            'ReportRecoverStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportRecoverStatus,
                    request_deserializer=recover__pb2.RecoverStatusRequest.FromString,
                    response_serializer=recover__pb2.Status.SerializeToString,
            ),
            'ReportProcessFault': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProcessFault,
                    request_deserializer=recover__pb2.ProcessFaultRequest.FromString,
                    response_serializer=recover__pb2.Status.SerializeToString,
            ),
            'SwitchNicTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchNicTrack,
                    request_deserializer=recover__pb2.SwitchNics.FromString,
                    response_serializer=recover__pb2.Status.SerializeToString,
            ),
            'SubscribeSwitchNicSignal': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeSwitchNicSignal,
                    request_deserializer=recover__pb2.SwitchNicRequest.FromString,
                    response_serializer=recover__pb2.SwitchNicResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=recover__pb2.ClientInfo.FromString,
                    response_serializer=recover__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Recover', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recover(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recover/Init',
            recover__pb2.ClientInfo.SerializeToString,
            recover__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recover/Register',
            recover__pb2.ClientInfo.SerializeToString,
            recover__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeProcessManageSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Recover/SubscribeProcessManageSignal',
            recover__pb2.ClientInfo.SerializeToString,
            recover__pb2.ProcessManageSignal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportStopComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recover/ReportStopComplete',
            recover__pb2.StopCompleteRequest.SerializeToString,
            recover__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportRecoverStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recover/ReportRecoverStrategy',
            recover__pb2.RecoverStrategyRequest.SerializeToString,
            recover__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportRecoverStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recover/ReportRecoverStatus',
            recover__pb2.RecoverStatusRequest.SerializeToString,
            recover__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportProcessFault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recover/ReportProcessFault',
            recover__pb2.ProcessFaultRequest.SerializeToString,
            recover__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SwitchNicTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recover/SwitchNicTrack',
            recover__pb2.SwitchNics.SerializeToString,
            recover__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeSwitchNicSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Recover/SubscribeSwitchNicSignal',
            recover__pb2.SwitchNicRequest.SerializeToString,
            recover__pb2.SwitchNicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recover/HealthCheck',
            recover__pb2.ClientInfo.SerializeToString,
            recover__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
