// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/recover.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0beebb6a1a69646, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ClientInfo struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0beebb6a1a69646, []int{1}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ClientInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type FaultRank struct {
	RankId               string   `protobuf:"bytes,1,opt,name=rankId,proto3" json:"rankId,omitempty"`
	FaultType            string   `protobuf:"bytes,2,opt,name=faultType,proto3" json:"faultType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaultRank) Reset()         { *m = FaultRank{} }
func (m *FaultRank) String() string { return proto.CompactTextString(m) }
func (*FaultRank) ProtoMessage()    {}
func (*FaultRank) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0beebb6a1a69646, []int{2}
}

func (m *FaultRank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaultRank.Unmarshal(m, b)
}
func (m *FaultRank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaultRank.Marshal(b, m, deterministic)
}
func (m *FaultRank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaultRank.Merge(m, src)
}
func (m *FaultRank) XXX_Size() int {
	return xxx_messageInfo_FaultRank.Size(m)
}
func (m *FaultRank) XXX_DiscardUnknown() {
	xxx_messageInfo_FaultRank.DiscardUnknown(m)
}

var xxx_messageInfo_FaultRank proto.InternalMessageInfo

func (m *FaultRank) GetRankId() string {
	if m != nil {
		return m.RankId
	}
	return ""
}

func (m *FaultRank) GetFaultType() string {
	if m != nil {
		return m.FaultType
	}
	return ""
}

type ProcessManageSignal struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	JobId                string       `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	SignalType           string       `protobuf:"bytes,3,opt,name=signalType,proto3" json:"signalType,omitempty"`
	Actions              []string     `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,5,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	ChangeStrategy       string       `protobuf:"bytes,6,opt,name=changeStrategy,proto3" json:"changeStrategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProcessManageSignal) Reset()         { *m = ProcessManageSignal{} }
func (m *ProcessManageSignal) String() string { return proto.CompactTextString(m) }
func (*ProcessManageSignal) ProtoMessage()    {}
func (*ProcessManageSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0beebb6a1a69646, []int{3}
}

func (m *ProcessManageSignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessManageSignal.Unmarshal(m, b)
}
func (m *ProcessManageSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessManageSignal.Marshal(b, m, deterministic)
}
func (m *ProcessManageSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessManageSignal.Merge(m, src)
}
func (m *ProcessManageSignal) XXX_Size() int {
	return xxx_messageInfo_ProcessManageSignal.Size(m)
}
func (m *ProcessManageSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessManageSignal.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessManageSignal proto.InternalMessageInfo

func (m *ProcessManageSignal) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ProcessManageSignal) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ProcessManageSignal) GetSignalType() string {
	if m != nil {
		return m.SignalType
	}
	return ""
}

func (m *ProcessManageSignal) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *ProcessManageSignal) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

func (m *ProcessManageSignal) GetChangeStrategy() string {
	if m != nil {
		return m.ChangeStrategy
	}
	return ""
}

type StopCompleteRequest struct {
	JobId                string       `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Status               *Status      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,3,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StopCompleteRequest) Reset()         { *m = StopCompleteRequest{} }
func (m *StopCompleteRequest) String() string { return proto.CompactTextString(m) }
func (*StopCompleteRequest) ProtoMessage()    {}
func (*StopCompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0beebb6a1a69646, []int{4}
}

func (m *StopCompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopCompleteRequest.Unmarshal(m, b)
}
func (m *StopCompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopCompleteRequest.Marshal(b, m, deterministic)
}
func (m *StopCompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopCompleteRequest.Merge(m, src)
}
func (m *StopCompleteRequest) XXX_Size() int {
	return xxx_messageInfo_StopCompleteRequest.Size(m)
}
func (m *StopCompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopCompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopCompleteRequest proto.InternalMessageInfo

func (m *StopCompleteRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *StopCompleteRequest) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StopCompleteRequest) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

type RecoverStrategyRequest struct {
	JobId                string       `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,2,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	Strategies           []string     `protobuf:"bytes,3,rep,name=strategies,proto3" json:"strategies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RecoverStrategyRequest) Reset()         { *m = RecoverStrategyRequest{} }
func (m *RecoverStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverStrategyRequest) ProtoMessage()    {}
func (*RecoverStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0beebb6a1a69646, []int{5}
}

func (m *RecoverStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverStrategyRequest.Unmarshal(m, b)
}
func (m *RecoverStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverStrategyRequest.Marshal(b, m, deterministic)
}
func (m *RecoverStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverStrategyRequest.Merge(m, src)
}
func (m *RecoverStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverStrategyRequest.Size(m)
}
func (m *RecoverStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverStrategyRequest proto.InternalMessageInfo

func (m *RecoverStrategyRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RecoverStrategyRequest) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

func (m *RecoverStrategyRequest) GetStrategies() []string {
	if m != nil {
		return m.Strategies
	}
	return nil
}

type RecoverStatusRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Strategy             string   `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverStatusRequest) Reset()         { *m = RecoverStatusRequest{} }
func (m *RecoverStatusRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverStatusRequest) ProtoMessage()    {}
func (*RecoverStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0beebb6a1a69646, []int{6}
}

func (m *RecoverStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverStatusRequest.Unmarshal(m, b)
}
func (m *RecoverStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverStatusRequest.Marshal(b, m, deterministic)
}
func (m *RecoverStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverStatusRequest.Merge(m, src)
}
func (m *RecoverStatusRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverStatusRequest.Size(m)
}
func (m *RecoverStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverStatusRequest proto.InternalMessageInfo

func (m *RecoverStatusRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RecoverStatusRequest) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RecoverStatusRequest) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

type ProcessFaultRequest struct {
	JobId                string       `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	FaultRanks           []*FaultRank `protobuf:"bytes,2,rep,name=faultRanks,proto3" json:"faultRanks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProcessFaultRequest) Reset()         { *m = ProcessFaultRequest{} }
func (m *ProcessFaultRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessFaultRequest) ProtoMessage()    {}
func (*ProcessFaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0beebb6a1a69646, []int{7}
}

func (m *ProcessFaultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessFaultRequest.Unmarshal(m, b)
}
func (m *ProcessFaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessFaultRequest.Marshal(b, m, deterministic)
}
func (m *ProcessFaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessFaultRequest.Merge(m, src)
}
func (m *ProcessFaultRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessFaultRequest.Size(m)
}
func (m *ProcessFaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessFaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessFaultRequest proto.InternalMessageInfo

func (m *ProcessFaultRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ProcessFaultRequest) GetFaultRanks() []*FaultRank {
	if m != nil {
		return m.FaultRanks
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*ClientInfo)(nil), "ClientInfo")
	proto.RegisterType((*FaultRank)(nil), "FaultRank")
	proto.RegisterType((*ProcessManageSignal)(nil), "ProcessManageSignal")
	proto.RegisterType((*StopCompleteRequest)(nil), "StopCompleteRequest")
	proto.RegisterType((*RecoverStrategyRequest)(nil), "RecoverStrategyRequest")
	proto.RegisterType((*RecoverStatusRequest)(nil), "RecoverStatusRequest")
	proto.RegisterType((*ProcessFaultRequest)(nil), "ProcessFaultRequest")
}

func init() {
	proto.RegisterFile("pb/recover.proto", fileDescriptor_f0beebb6a1a69646)
}

var fileDescriptor_f0beebb6a1a69646 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x5e, 0xda, 0x2e, 0x5d, 0x5e, 0x25, 0x84, 0xdc, 0x6e, 0x44, 0xd3, 0x34, 0x2a, 0x1f, 0x50,
	0xc5, 0xc1, 0x4c, 0x45, 0xc0, 0x61, 0x27, 0x98, 0x40, 0xea, 0x01, 0x09, 0x39, 0x48, 0x48, 0xdc,
	0x9c, 0xcc, 0x0d, 0x66, 0xc1, 0x0e, 0xb6, 0x83, 0x18, 0xff, 0x91, 0xff, 0xc3, 0x11, 0xc5, 0x69,
	0x52, 0xaf, 0xca, 0x7a, 0x81, 0xdb, 0x7b, 0xcf, 0xfe, 0xfc, 0xbe, 0xef, 0xbd, 0x2f, 0x81, 0x87,
	0x65, 0xfa, 0x4c, 0xf3, 0x4c, 0xfd, 0xe0, 0x9a, 0x94, 0x5a, 0x59, 0x85, 0x2f, 0x20, 0x4c, 0x2c,
	0xb3, 0x95, 0x41, 0x08, 0x46, 0x99, 0xba, 0xe6, 0x71, 0x30, 0x0f, 0x16, 0x87, 0xd4, 0xc5, 0x75,
	0x4d, 0xc8, 0xb5, 0x8a, 0x07, 0xf3, 0x60, 0x11, 0x51, 0x17, 0xe3, 0x97, 0x00, 0x57, 0x85, 0xe0,
	0xd2, 0xae, 0xe4, 0x5a, 0xa1, 0x19, 0x1c, 0x7e, 0x55, 0xe9, 0xea, 0xda, 0xc1, 0x22, 0xda, 0x24,
	0x35, 0x4e, 0xab, 0x82, 0xb7, 0xb8, 0x3a, 0xc6, 0xaf, 0x21, 0x7a, 0xc7, 0xaa, 0xc2, 0x52, 0x26,
	0x6f, 0xd0, 0x09, 0x84, 0x9a, 0xc9, 0x9b, 0x0e, 0xb7, 0xc9, 0xd0, 0x19, 0x44, 0xeb, 0xfa, 0xd2,
	0xc7, 0xdb, 0xb2, 0x45, 0x6f, 0x0b, 0xf8, 0x77, 0x00, 0xd3, 0x0f, 0x5a, 0x65, 0xdc, 0x98, 0xf7,
	0x4c, 0xb2, 0x9c, 0x27, 0x22, 0x97, 0xac, 0xa8, 0xdb, 0x55, 0x95, 0x68, 0xdf, 0x72, 0xf1, 0x96,
	0xd8, 0xc0, 0x27, 0x76, 0x0e, 0x60, 0x1c, 0xc6, 0x35, 0x18, 0xba, 0x23, 0xaf, 0x82, 0x62, 0x18,
	0xb3, 0xcc, 0x0a, 0x25, 0x4d, 0x3c, 0x9a, 0x0f, 0x17, 0x11, 0x6d, 0x53, 0xf4, 0x14, 0x60, 0xdd,
	0xd2, 0x37, 0xf1, 0xe1, 0x7c, 0xb8, 0x98, 0x2c, 0x81, 0x74, 0x8a, 0xa8, 0x77, 0x8a, 0x9e, 0xc0,
	0x83, 0xec, 0x0b, 0x93, 0x39, 0x4f, 0xac, 0x66, 0x96, 0xe7, 0xb7, 0x71, 0xe8, 0x3a, 0xed, 0x54,
	0xf1, 0x4f, 0x98, 0x26, 0x56, 0x95, 0x57, 0xea, 0x5b, 0x59, 0x70, 0xcb, 0x29, 0xff, 0x5e, 0x71,
	0x63, 0xef, 0x99, 0xe9, 0x63, 0x08, 0x8d, 0xdb, 0x94, 0x53, 0x34, 0x59, 0x8e, 0x49, 0xb3, 0x38,
	0xba, 0x29, 0xef, 0x30, 0x1c, 0xee, 0x63, 0x88, 0x7f, 0xc1, 0x09, 0x6d, 0x7c, 0xd0, 0x92, 0xd9,
	0xdf, 0xfc, 0xee, 0xdb, 0x83, 0xbd, 0xea, 0xeb, 0x19, 0x37, 0x8f, 0x0a, 0xde, 0xf0, 0xa8, 0x67,
	0xdc, 0x55, 0xb0, 0x80, 0x59, 0xd7, 0xdb, 0x09, 0xf8, 0x37, 0xd9, 0xa7, 0x70, 0x64, 0xda, 0x31,
	0x37, 0x0b, 0xed, 0x72, 0xfc, 0xa9, 0xf3, 0x4b, 0x43, 0xf5, 0x7f, 0x69, 0x5c, 0xfe, 0x19, 0xc0,
	0x78, 0x23, 0x02, 0x9d, 0xc3, 0x68, 0x25, 0x85, 0x45, 0x13, 0xb2, 0xfd, 0x2e, 0x4e, 0x5b, 0x9a,
	0xf8, 0x00, 0x61, 0x38, 0xa2, 0x3c, 0x17, 0xc6, 0x72, 0x7d, 0xef, 0x9d, 0xb7, 0x70, 0x96, 0x54,
	0xa9, 0xc9, 0xb4, 0x48, 0x79, 0x9f, 0xc3, 0xef, 0xe0, 0x66, 0xa4, 0xe7, 0x0a, 0x3e, 0xb8, 0x08,
	0xd0, 0x0b, 0x40, 0x94, 0x97, 0x4a, 0x5b, 0xdf, 0x56, 0x68, 0x46, 0x7a, 0x5c, 0xe6, 0x77, 0xbf,
	0x84, 0xe3, 0x06, 0xb6, 0xe3, 0x09, 0xf4, 0x88, 0xf4, 0xbb, 0xc4, 0x07, 0xbf, 0x82, 0xe9, 0x0e,
	0xd8, 0xad, 0xe5, 0x98, 0xf4, 0x2d, 0xd9, 0x07, 0x76, 0x64, 0xfd, 0x15, 0xa1, 0x4e, 0x9c, 0xbf,
	0x31, 0x0f, 0xf6, 0x26, 0xfc, 0x3c, 0x22, 0x97, 0x65, 0x9a, 0x86, 0xee, 0x07, 0xf6, 0xfc, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x18, 0xdd, 0xb7, 0xd4, 0x04, 0x00, 0x00,
}
