// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc v5.27.0
// source: pb/recover.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Recover_Register_FullMethodName                     = "/Recover/Register"
	Recover_NotifyStepRetry_FullMethodName              = "/Recover/NotifyStepRetry"
	Recover_NotifyRetryStatus_FullMethodName            = "/Recover/NotifyRetryStatus"
	Recover_SubscribeProcessManageSignal_FullMethodName = "/Recover/SubscribeProcessManageSignal"
	Recover_ReportStopComplete_FullMethodName           = "/Recover/ReportStopComplete"
	Recover_ReportRecoverStrategy_FullMethodName        = "/Recover/ReportRecoverStrategy"
	Recover_ReportRecoverStatus_FullMethodName          = "/Recover/ReportRecoverStatus"
	Recover_ReportProcessFault_FullMethodName           = "/Recover/ReportProcessFault"
)

// RecoverClient is the client API for Recover service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecoverClient interface {
	Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error)
	// hbm fault recover interface
	NotifyStepRetry(ctx context.Context, in *NotifyStepRetryRequest, opts ...grpc.CallOption) (*Status, error)
	NotifyRetryStatus(ctx context.Context, in *NotifyRetryStatusRequest, opts ...grpc.CallOption) (*Status, error)
	// process recover interface
	SubscribeProcessManageSignal(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Recover_SubscribeProcessManageSignalClient, error)
	ReportStopComplete(ctx context.Context, in *StopCompleteRequest, opts ...grpc.CallOption) (*Status, error)
	ReportRecoverStrategy(ctx context.Context, in *RecoverStrategyRequest, opts ...grpc.CallOption) (*RecoverStrategyResponse, error)
	ReportRecoverStatus(ctx context.Context, in *RecoverStatusRequest, opts ...grpc.CallOption) (*Status, error)
	ReportProcessFault(ctx context.Context, in *ProcessFaultRequest, opts ...grpc.CallOption) (*Status, error)
}

type recoverClient struct {
	cc grpc.ClientConnInterface
}

func NewRecoverClient(cc grpc.ClientConnInterface) RecoverClient {
	return &recoverClient{cc}
}

func (c *recoverClient) Register(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) NotifyStepRetry(ctx context.Context, in *NotifyStepRetryRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_NotifyStepRetry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) NotifyRetryStatus(ctx context.Context, in *NotifyRetryStatusRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_NotifyRetryStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) SubscribeProcessManageSignal(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (Recover_SubscribeProcessManageSignalClient, error) {
	stream, err := c.cc.NewStream(ctx, &Recover_ServiceDesc.Streams[0], Recover_SubscribeProcessManageSignal_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &recoverSubscribeProcessManageSignalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Recover_SubscribeProcessManageSignalClient interface {
	Recv() (*ProcessManageSignal, error)
	grpc.ClientStream
}

type recoverSubscribeProcessManageSignalClient struct {
	grpc.ClientStream
}

func (x *recoverSubscribeProcessManageSignalClient) Recv() (*ProcessManageSignal, error) {
	m := new(ProcessManageSignal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recoverClient) ReportStopComplete(ctx context.Context, in *StopCompleteRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_ReportStopComplete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) ReportRecoverStrategy(ctx context.Context, in *RecoverStrategyRequest, opts ...grpc.CallOption) (*RecoverStrategyResponse, error) {
	out := new(RecoverStrategyResponse)
	err := c.cc.Invoke(ctx, Recover_ReportRecoverStrategy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) ReportRecoverStatus(ctx context.Context, in *RecoverStatusRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_ReportRecoverStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoverClient) ReportProcessFault(ctx context.Context, in *ProcessFaultRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Recover_ReportProcessFault_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecoverServer is the server API for Recover service.
// All implementations must embed UnimplementedRecoverServer
// for forward compatibility
type RecoverServer interface {
	Register(context.Context, *ClientInfo) (*Status, error)
	// hbm fault recover interface
	NotifyStepRetry(context.Context, *NotifyStepRetryRequest) (*Status, error)
	NotifyRetryStatus(context.Context, *NotifyRetryStatusRequest) (*Status, error)
	// process recover interface
	SubscribeProcessManageSignal(*ClientInfo, Recover_SubscribeProcessManageSignalServer) error
	ReportStopComplete(context.Context, *StopCompleteRequest) (*Status, error)
	ReportRecoverStrategy(context.Context, *RecoverStrategyRequest) (*RecoverStrategyResponse, error)
	ReportRecoverStatus(context.Context, *RecoverStatusRequest) (*Status, error)
	ReportProcessFault(context.Context, *ProcessFaultRequest) (*Status, error)
	mustEmbedUnimplementedRecoverServer()
}

// UnimplementedRecoverServer must be embedded to have forward compatible implementations.
type UnimplementedRecoverServer struct {
}

func (UnimplementedRecoverServer) Register(context.Context, *ClientInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRecoverServer) NotifyStepRetry(context.Context, *NotifyStepRetryRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyStepRetry not implemented")
}
func (UnimplementedRecoverServer) NotifyRetryStatus(context.Context, *NotifyRetryStatusRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyRetryStatus not implemented")
}
func (UnimplementedRecoverServer) SubscribeProcessManageSignal(*ClientInfo, Recover_SubscribeProcessManageSignalServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeProcessManageSignal not implemented")
}
func (UnimplementedRecoverServer) ReportStopComplete(context.Context, *StopCompleteRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStopComplete not implemented")
}
func (UnimplementedRecoverServer) ReportRecoverStrategy(context.Context, *RecoverStrategyRequest) (*RecoverStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportRecoverStrategy not implemented")
}
func (UnimplementedRecoverServer) ReportRecoverStatus(context.Context, *RecoverStatusRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportRecoverStatus not implemented")
}
func (UnimplementedRecoverServer) ReportProcessFault(context.Context, *ProcessFaultRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportProcessFault not implemented")
}
func (UnimplementedRecoverServer) mustEmbedUnimplementedRecoverServer() {}

// UnsafeRecoverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecoverServer will
// result in compilation errors.
type UnsafeRecoverServer interface {
	mustEmbedUnimplementedRecoverServer()
}

func RegisterRecoverServer(s grpc.ServiceRegistrar, srv RecoverServer) {
	s.RegisterService(&Recover_ServiceDesc, srv)
}

func _Recover_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).Register(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_NotifyStepRetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyStepRetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).NotifyStepRetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_NotifyStepRetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).NotifyStepRetry(ctx, req.(*NotifyStepRetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_NotifyRetryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRetryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).NotifyRetryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_NotifyRetryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).NotifyRetryStatus(ctx, req.(*NotifyRetryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_SubscribeProcessManageSignal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecoverServer).SubscribeProcessManageSignal(m, &recoverSubscribeProcessManageSignalServer{stream})
}

type Recover_SubscribeProcessManageSignalServer interface {
	Send(*ProcessManageSignal) error
	grpc.ServerStream
}

type recoverSubscribeProcessManageSignalServer struct {
	grpc.ServerStream
}

func (x *recoverSubscribeProcessManageSignalServer) Send(m *ProcessManageSignal) error {
	return x.ServerStream.SendMsg(m)
}

func _Recover_ReportStopComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).ReportStopComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_ReportStopComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).ReportStopComplete(ctx, req.(*StopCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_ReportRecoverStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).ReportRecoverStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_ReportRecoverStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).ReportRecoverStrategy(ctx, req.(*RecoverStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_ReportRecoverStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).ReportRecoverStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_ReportRecoverStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).ReportRecoverStatus(ctx, req.(*RecoverStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recover_ReportProcessFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoverServer).ReportProcessFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recover_ReportProcessFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoverServer).ReportProcessFault(ctx, req.(*ProcessFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Recover_ServiceDesc is the grpc.ServiceDesc for Recover service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recover_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Recover",
	HandlerType: (*RecoverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Recover_Register_Handler,
		},
		{
			MethodName: "NotifyStepRetry",
			Handler:    _Recover_NotifyStepRetry_Handler,
		},
		{
			MethodName: "NotifyRetryStatus",
			Handler:    _Recover_NotifyRetryStatus_Handler,
		},
		{
			MethodName: "ReportStopComplete",
			Handler:    _Recover_ReportStopComplete_Handler,
		},
		{
			MethodName: "ReportRecoverStrategy",
			Handler:    _Recover_ReportRecoverStrategy_Handler,
		},
		{
			MethodName: "ReportRecoverStatus",
			Handler:    _Recover_ReportRecoverStatus_Handler,
		},
		{
			MethodName: "ReportProcessFault",
			Handler:    _Recover_ReportProcessFault_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeProcessManageSignal",
			Handler:       _Recover_SubscribeProcessManageSignal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/recover.proto",
}
