// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pubfault.proto

package pb2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// different services with the same name may result in errors
type RespStatus struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespStatus) Reset()         { *m = RespStatus{} }
func (m *RespStatus) String() string { return proto.CompactTextString(m) }
func (*RespStatus) ProtoMessage()    {}
func (*RespStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a19729a49216baa, []int{0}
}

func (m *RespStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespStatus.Unmarshal(m, b)
}
func (m *RespStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespStatus.Marshal(b, m, deterministic)
}
func (m *RespStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespStatus.Merge(m, src)
}
func (m *RespStatus) XXX_Size() int {
	return xxx_messageInfo_RespStatus.Size(m)
}
func (m *RespStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RespStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RespStatus proto.InternalMessageInfo

func (m *RespStatus) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespStatus) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type PublicFaultRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Resource             string   `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Faults               []*Fault `protobuf:"bytes,5,rep,name=faults,proto3" json:"faults,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicFaultRequest) Reset()         { *m = PublicFaultRequest{} }
func (m *PublicFaultRequest) String() string { return proto.CompactTextString(m) }
func (*PublicFaultRequest) ProtoMessage()    {}
func (*PublicFaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a19729a49216baa, []int{1}
}

func (m *PublicFaultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicFaultRequest.Unmarshal(m, b)
}
func (m *PublicFaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicFaultRequest.Marshal(b, m, deterministic)
}
func (m *PublicFaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicFaultRequest.Merge(m, src)
}
func (m *PublicFaultRequest) XXX_Size() int {
	return xxx_messageInfo_PublicFaultRequest.Size(m)
}
func (m *PublicFaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicFaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicFaultRequest proto.InternalMessageInfo

func (m *PublicFaultRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PublicFaultRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PublicFaultRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PublicFaultRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *PublicFaultRequest) GetFaults() []*Fault {
	if m != nil {
		return m.Faults
	}
	return nil
}

type Fault struct {
	FaultId              string            `protobuf:"bytes,1,opt,name=faultId,proto3" json:"faultId,omitempty"`
	FaultType            string            `protobuf:"bytes,2,opt,name=faultType,proto3" json:"faultType,omitempty"`
	FaultCode            string            `protobuf:"bytes,3,opt,name=faultCode,proto3" json:"faultCode,omitempty"`
	FaultTime            int64             `protobuf:"varint,4,opt,name=faultTime,proto3" json:"faultTime,omitempty"`
	Assertion            string            `protobuf:"bytes,5,opt,name=assertion,proto3" json:"assertion,omitempty"`
	FaultLocation        map[string]string `protobuf:"bytes,6,rep,name=faultLocation,proto3" json:"faultLocation,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Influence            []*PubFaultInfo   `protobuf:"bytes,7,rep,name=influence,proto3" json:"influence,omitempty"`
	Description          string            `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Fault) Reset()         { *m = Fault{} }
func (m *Fault) String() string { return proto.CompactTextString(m) }
func (*Fault) ProtoMessage()    {}
func (*Fault) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a19729a49216baa, []int{2}
}

func (m *Fault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fault.Unmarshal(m, b)
}
func (m *Fault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fault.Marshal(b, m, deterministic)
}
func (m *Fault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fault.Merge(m, src)
}
func (m *Fault) XXX_Size() int {
	return xxx_messageInfo_Fault.Size(m)
}
func (m *Fault) XXX_DiscardUnknown() {
	xxx_messageInfo_Fault.DiscardUnknown(m)
}

var xxx_messageInfo_Fault proto.InternalMessageInfo

func (m *Fault) GetFaultId() string {
	if m != nil {
		return m.FaultId
	}
	return ""
}

func (m *Fault) GetFaultType() string {
	if m != nil {
		return m.FaultType
	}
	return ""
}

func (m *Fault) GetFaultCode() string {
	if m != nil {
		return m.FaultCode
	}
	return ""
}

func (m *Fault) GetFaultTime() int64 {
	if m != nil {
		return m.FaultTime
	}
	return 0
}

func (m *Fault) GetAssertion() string {
	if m != nil {
		return m.Assertion
	}
	return ""
}

func (m *Fault) GetFaultLocation() map[string]string {
	if m != nil {
		return m.FaultLocation
	}
	return nil
}

func (m *Fault) GetInfluence() []*PubFaultInfo {
	if m != nil {
		return m.Influence
	}
	return nil
}

func (m *Fault) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type PubFaultInfo struct {
	NodeName             string   `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	DeviceIds            []int32  `protobuf:"varint,2,rep,packed,name=deviceIds,proto3" json:"deviceIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubFaultInfo) Reset()         { *m = PubFaultInfo{} }
func (m *PubFaultInfo) String() string { return proto.CompactTextString(m) }
func (*PubFaultInfo) ProtoMessage()    {}
func (*PubFaultInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a19729a49216baa, []int{3}
}

func (m *PubFaultInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubFaultInfo.Unmarshal(m, b)
}
func (m *PubFaultInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubFaultInfo.Marshal(b, m, deterministic)
}
func (m *PubFaultInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubFaultInfo.Merge(m, src)
}
func (m *PubFaultInfo) XXX_Size() int {
	return xxx_messageInfo_PubFaultInfo.Size(m)
}
func (m *PubFaultInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PubFaultInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PubFaultInfo proto.InternalMessageInfo

func (m *PubFaultInfo) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *PubFaultInfo) GetDeviceIds() []int32 {
	if m != nil {
		return m.DeviceIds
	}
	return nil
}

func init() {
	proto.RegisterType((*RespStatus)(nil), "RespStatus")
	proto.RegisterType((*PublicFaultRequest)(nil), "PublicFaultRequest")
	proto.RegisterType((*Fault)(nil), "Fault")
	proto.RegisterMapType((map[string]string)(nil), "Fault.FaultLocationEntry")
	proto.RegisterType((*PubFaultInfo)(nil), "PubFaultInfo")
}

func init() {
	proto.RegisterFile("pubfault.proto", fileDescriptor_8a19729a49216baa)
}

var fileDescriptor_8a19729a49216baa = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x5d, 0xab, 0xd3, 0x40,
	0x10, 0x35, 0xc9, 0x4d, 0x3f, 0xa6, 0xde, 0xab, 0x8c, 0x3e, 0xc4, 0x22, 0x12, 0xf2, 0x54, 0x10,
	0xf2, 0x50, 0x15, 0x44, 0x1f, 0xfc, 0x42, 0xb1, 0x20, 0x72, 0xd9, 0xeb, 0x93, 0x6f, 0xf9, 0x98,
	0xc2, 0x62, 0xbb, 0x1b, 0xb3, 0xbb, 0x85, 0xfe, 0x13, 0xff, 0xa3, 0x7f, 0x42, 0x76, 0xd2, 0x34,
	0x91, 0xbe, 0x84, 0x99, 0x73, 0xf6, 0xcc, 0x9c, 0x99, 0x0c, 0xdc, 0x34, 0xae, 0xdc, 0x16, 0x6e,
	0x67, 0xf3, 0xa6, 0xd5, 0x56, 0x67, 0x2f, 0x01, 0x04, 0x99, 0xe6, 0xce, 0x16, 0xd6, 0x19, 0x44,
	0xb8, 0xaa, 0x74, 0x4d, 0x49, 0x90, 0x06, 0xab, 0x58, 0x70, 0xec, 0x31, 0xa9, 0xb6, 0x3a, 0x09,
	0xd3, 0x60, 0x35, 0x17, 0x1c, 0x67, 0x7f, 0x02, 0xc0, 0x5b, 0x57, 0xee, 0x64, 0xf5, 0xc5, 0xd7,
	0x12, 0xf4, 0xdb, 0x91, 0xb1, 0x78, 0x03, 0xa1, 0xac, 0x59, 0x3c, 0x17, 0xa1, 0xac, 0xf1, 0x29,
	0xcc, 0xad, 0xdc, 0x93, 0xb1, 0xc5, 0xbe, 0x61, 0x7d, 0x24, 0x06, 0x00, 0x13, 0x98, 0x1e, 0xa8,
	0x35, 0x52, 0xab, 0x24, 0x62, 0x49, 0x9f, 0xe2, 0x12, 0x66, 0x2d, 0x19, 0xed, 0xda, 0x8a, 0x92,
	0x2b, 0xa6, 0xce, 0x39, 0x3e, 0x83, 0x09, 0xfb, 0x37, 0x49, 0x9c, 0x46, 0xab, 0xc5, 0x7a, 0x92,
	0x77, 0x16, 0x4e, 0x68, 0xf6, 0x37, 0x84, 0x98, 0x11, 0x5f, 0x9f, 0xb1, 0x4d, 0x6f, 0xa9, 0x4f,
	0xbd, 0x2f, 0x0e, 0x7f, 0x1c, 0x1b, 0x3a, 0xcd, 0x35, 0x00, 0x67, 0xf6, 0x93, 0xdf, 0x44, 0x34,
	0x62, 0x3d, 0x30, 0x68, 0xe5, 0xbe, 0x33, 0x17, 0x89, 0x01, 0xf0, 0x6c, 0x61, 0x0c, 0xb5, 0xd6,
	0x4f, 0x15, 0x77, 0xda, 0x33, 0x80, 0xef, 0xe0, 0x9a, 0x9f, 0x7e, 0xd3, 0x55, 0xc1, 0x2f, 0x26,
	0x3c, 0xc2, 0x93, 0x6e, 0x84, 0xee, 0xdb, 0x73, 0x9f, 0x95, 0x6d, 0x8f, 0xe2, 0xff, 0xf7, 0xf8,
	0x1c, 0xe6, 0x52, 0x6d, 0x77, 0x8e, 0x54, 0x45, 0xc9, 0x94, 0xc5, 0xd7, 0xf9, 0xad, 0x2b, 0x59,
	0xb9, 0x51, 0x5b, 0x2d, 0x06, 0x1e, 0x53, 0x58, 0xd4, 0x64, 0xaa, 0x56, 0x36, 0xdc, 0x6b, 0xc6,
	0x6e, 0xc6, 0xd0, 0xf2, 0x3d, 0xe0, 0x65, 0x4f, 0x7c, 0x08, 0xd1, 0x2f, 0x3a, 0x9e, 0x76, 0xe6,
	0x43, 0x7c, 0x0c, 0xf1, 0xa1, 0xd8, 0xb9, 0x7e, 0x57, 0x5d, 0xf2, 0x26, 0x7c, 0x1d, 0x64, 0x5f,
	0xe1, 0xfe, 0xb8, 0xbd, 0xff, 0x73, 0x4a, 0xd7, 0xf4, 0xbd, 0xd8, 0xd3, 0xa9, 0xc0, 0x39, 0xf7,
	0xbb, 0xa9, 0xe9, 0x20, 0x2b, 0xda, 0xd4, 0x26, 0x09, 0xd3, 0x68, 0x15, 0x8b, 0x01, 0x58, 0x7f,
	0x80, 0x59, 0x5f, 0x09, 0x5f, 0xc1, 0x83, 0x3b, 0x52, 0xf5, 0xe8, 0xc2, 0xf0, 0x51, 0x7e, 0x79,
	0x6f, 0xcb, 0x45, 0x3e, 0xdc, 0x6e, 0x76, 0xef, 0xe3, 0xf4, 0x67, 0x9c, 0xbf, 0x6d, 0xca, 0x75,
	0x39, 0xe1, 0xdb, 0x7e, 0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x2e, 0xbc, 0xa8, 0xed, 0x02,
	0x00, 0x00,
}
