// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: pubfault.proto

package pb2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PubFault_SendPublicFault_FullMethodName = "/PubFault/SendPublicFault"
)

// PubFaultClient is the client API for PubFault service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PubFaultClient interface {
	SendPublicFault(ctx context.Context, in *PublicFaultRequest, opts ...grpc.CallOption) (*Status, error)
}

type pubFaultClient struct {
	cc grpc.ClientConnInterface
}

func NewPubFaultClient(cc grpc.ClientConnInterface) PubFaultClient {
	return &pubFaultClient{cc}
}

func (c *pubFaultClient) SendPublicFault(ctx context.Context, in *PublicFaultRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, PubFault_SendPublicFault_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PubFaultServer is the server API for PubFault service.
// All implementations must embed UnimplementedPubFaultServer
// for forward compatibility
type PubFaultServer interface {
	SendPublicFault(context.Context, *PublicFaultRequest) (*Status, error)
	mustEmbedUnimplementedPubFaultServer()
}

// UnimplementedPubFaultServer must be embedded to have forward compatible implementations.
type UnimplementedPubFaultServer struct {
}

func (UnimplementedPubFaultServer) SendPublicFault(context.Context, *PublicFaultRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPublicFault not implemented")
}
func (UnimplementedPubFaultServer) mustEmbedUnimplementedPubFaultServer() {}

// UnsafePubFaultServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PubFaultServer will
// result in compilation errors.
type UnsafePubFaultServer interface {
	mustEmbedUnimplementedPubFaultServer()
}

func RegisterPubFaultServer(s grpc.ServiceRegistrar, srv PubFaultServer) {
	s.RegisterService(&PubFault_ServiceDesc, srv)
}

func _PubFault_SendPublicFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubFaultServer).SendPublicFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubFault_SendPublicFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubFaultServer).SendPublicFault(ctx, req.(*PublicFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PubFault_ServiceDesc is the grpc.ServiceDesc for PubFault service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PubFault_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PubFault",
	HandlerType: (*PubFaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPublicFault",
			Handler:    _PubFault_SendPublicFault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pubfault.proto",
}
