// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: profiling.proto

package profiling

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TrainingDataTrace_ModifyTrainingDataTraceSwitch_FullMethodName = "/TrainingDataTrace/ModifyTrainingDataTraceSwitch"
	TrainingDataTrace_GetTrainingDataTraceSwitch_FullMethodName    = "/TrainingDataTrace/GetTrainingDataTraceSwitch"
)

// TrainingDataTraceClient is the client API for TrainingDataTrace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainingDataTraceClient interface {
	ModifyTrainingDataTraceSwitch(ctx context.Context, in *DataTypeReq, opts ...grpc.CallOption) (*DataTypeRes, error)
	GetTrainingDataTraceSwitch(ctx context.Context, in *DataStatusReq, opts ...grpc.CallOption) (*DataStatusRes, error)
}

type trainingDataTraceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingDataTraceClient(cc grpc.ClientConnInterface) TrainingDataTraceClient {
	return &trainingDataTraceClient{cc}
}

func (c *trainingDataTraceClient) ModifyTrainingDataTraceSwitch(ctx context.Context, in *DataTypeReq, opts ...grpc.CallOption) (*DataTypeRes, error) {
	out := new(DataTypeRes)
	err := c.cc.Invoke(ctx, TrainingDataTrace_ModifyTrainingDataTraceSwitch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingDataTraceClient) GetTrainingDataTraceSwitch(ctx context.Context, in *DataStatusReq, opts ...grpc.CallOption) (*DataStatusRes, error) {
	out := new(DataStatusRes)
	err := c.cc.Invoke(ctx, TrainingDataTrace_GetTrainingDataTraceSwitch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainingDataTraceServer is the server API for TrainingDataTrace service.
// All implementations must embed UnimplementedTrainingDataTraceServer
// for forward compatibility
type TrainingDataTraceServer interface {
	ModifyTrainingDataTraceSwitch(context.Context, *DataTypeReq) (*DataTypeRes, error)
	GetTrainingDataTraceSwitch(context.Context, *DataStatusReq) (*DataStatusRes, error)
	mustEmbedUnimplementedTrainingDataTraceServer()
}

// UnimplementedTrainingDataTraceServer must be embedded to have forward compatible implementations.
type UnimplementedTrainingDataTraceServer struct {
}

func (UnimplementedTrainingDataTraceServer) ModifyTrainingDataTraceSwitch(context.Context, *DataTypeReq) (*DataTypeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyTrainingDataTraceSwitch not implemented")
}
func (UnimplementedTrainingDataTraceServer) GetTrainingDataTraceSwitch(context.Context, *DataStatusReq) (*DataStatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrainingDataTraceSwitch not implemented")
}
func (UnimplementedTrainingDataTraceServer) mustEmbedUnimplementedTrainingDataTraceServer() {}

// UnsafeTrainingDataTraceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingDataTraceServer will
// result in compilation errors.
type UnsafeTrainingDataTraceServer interface {
	mustEmbedUnimplementedTrainingDataTraceServer()
}

func RegisterTrainingDataTraceServer(s grpc.ServiceRegistrar, srv TrainingDataTraceServer) {
	s.RegisterService(&TrainingDataTrace_ServiceDesc, srv)
}

func _TrainingDataTrace_ModifyTrainingDataTraceSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingDataTraceServer).ModifyTrainingDataTraceSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingDataTrace_ModifyTrainingDataTraceSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingDataTraceServer).ModifyTrainingDataTraceSwitch(ctx, req.(*DataTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingDataTrace_GetTrainingDataTraceSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingDataTraceServer).GetTrainingDataTraceSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingDataTrace_GetTrainingDataTraceSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingDataTraceServer).GetTrainingDataTraceSwitch(ctx, req.(*DataStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TrainingDataTrace_ServiceDesc is the grpc.ServiceDesc for TrainingDataTrace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainingDataTrace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TrainingDataTrace",
	HandlerType: (*TrainingDataTraceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModifyTrainingDataTraceSwitch",
			Handler:    _TrainingDataTrace_ModifyTrainingDataTraceSwitch_Handler,
		},
		{
			MethodName: "GetTrainingDataTraceSwitch",
			Handler:    _TrainingDataTrace_GetTrainingDataTraceSwitch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profiling.proto",
}
