// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: proto/tasknet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TaskNet_Register_FullMethodName             = "/TaskNet/Register"
	TaskNet_PathDiscovery_FullMethodName        = "/TaskNet/PathDiscovery"
	TaskNet_TransferMessage_FullMethodName      = "/TaskNet/TransferMessage"
	TaskNet_InitServerDownStream_FullMethodName = "/TaskNet/InitServerDownStream"
)

// TaskNetClient is the client API for TaskNet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskNetClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Ack, error)
	PathDiscovery(ctx context.Context, in *PathDiscoveryReq, opts ...grpc.CallOption) (*Ack, error)
	TransferMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error)
	InitServerDownStream(ctx context.Context, opts ...grpc.CallOption) (TaskNet_InitServerDownStreamClient, error)
}

type taskNetClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskNetClient(cc grpc.ClientConnInterface) TaskNetClient {
	return &taskNetClient{cc}
}

func (c *taskNetClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, TaskNet_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNetClient) PathDiscovery(ctx context.Context, in *PathDiscoveryReq, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, TaskNet_PathDiscovery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNetClient) TransferMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, TaskNet_TransferMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskNetClient) InitServerDownStream(ctx context.Context, opts ...grpc.CallOption) (TaskNet_InitServerDownStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &TaskNet_ServiceDesc.Streams[0], TaskNet_InitServerDownStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &taskNetInitServerDownStreamClient{stream}
	return x, nil
}

type TaskNet_InitServerDownStreamClient interface {
	Send(*Ack) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type taskNetInitServerDownStreamClient struct {
	grpc.ClientStream
}

func (x *taskNetInitServerDownStreamClient) Send(m *Ack) error {
	return x.ClientStream.SendMsg(m)
}

func (x *taskNetInitServerDownStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskNetServer is the server API for TaskNet service.
// All implementations must embed UnimplementedTaskNetServer
// for forward compatibility
type TaskNetServer interface {
	Register(context.Context, *RegisterReq) (*Ack, error)
	PathDiscovery(context.Context, *PathDiscoveryReq) (*Ack, error)
	TransferMessage(context.Context, *Message) (*Ack, error)
	InitServerDownStream(TaskNet_InitServerDownStreamServer) error
	mustEmbedUnimplementedTaskNetServer()
}

// UnimplementedTaskNetServer must be embedded to have forward compatible implementations.
type UnimplementedTaskNetServer struct {
}

func (UnimplementedTaskNetServer) Register(context.Context, *RegisterReq) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedTaskNetServer) PathDiscovery(context.Context, *PathDiscoveryReq) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PathDiscovery not implemented")
}
func (UnimplementedTaskNetServer) TransferMessage(context.Context, *Message) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferMessage not implemented")
}
func (UnimplementedTaskNetServer) InitServerDownStream(TaskNet_InitServerDownStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method InitServerDownStream not implemented")
}
func (UnimplementedTaskNetServer) mustEmbedUnimplementedTaskNetServer() {}

// UnsafeTaskNetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskNetServer will
// result in compilation errors.
type UnsafeTaskNetServer interface {
	mustEmbedUnimplementedTaskNetServer()
}

func RegisterTaskNetServer(s grpc.ServiceRegistrar, srv TaskNetServer) {
	s.RegisterService(&TaskNet_ServiceDesc, srv)
}

func _TaskNet_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNetServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNet_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNetServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNet_PathDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathDiscoveryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNetServer).PathDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNet_PathDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNetServer).PathDiscovery(ctx, req.(*PathDiscoveryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNet_TransferMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskNetServer).TransferMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskNet_TransferMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskNetServer).TransferMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskNet_InitServerDownStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskNetServer).InitServerDownStream(&taskNetInitServerDownStreamServer{stream})
}

type TaskNet_InitServerDownStreamServer interface {
	Send(*Message) error
	Recv() (*Ack, error)
	grpc.ServerStream
}

type taskNetInitServerDownStreamServer struct {
	grpc.ServerStream
}

func (x *taskNetInitServerDownStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *taskNetInitServerDownStreamServer) Recv() (*Ack, error) {
	m := new(Ack)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskNet_ServiceDesc is the grpc.ServiceDesc for TaskNet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskNet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TaskNet",
	HandlerType: (*TaskNetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _TaskNet_Register_Handler,
		},
		{
			MethodName: "PathDiscovery",
			Handler:    _TaskNet_PathDiscovery_Handler,
		},
		{
			MethodName: "TransferMessage",
			Handler:    _TaskNet_TransferMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InitServerDownStream",
			Handler:       _TaskNet_InitServerDownStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/tasknet.proto",
}
