// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tasknet.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Position struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	ServerRank           string   `protobuf:"bytes,2,opt,name=serverRank,proto3" json:"serverRank,omitempty"`
	ProcessRank          string   `protobuf:"bytes,3,opt,name=processRank,proto3" json:"processRank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_0beab0884e07f523, []int{0}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Position) GetServerRank() string {
	if m != nil {
		return m.ServerRank
	}
	return ""
}

func (m *Position) GetProcessRank() string {
	if m != nil {
		return m.ProcessRank
	}
	return ""
}

type RegisterReq struct {
	Uuid                 string    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pos                  *Position `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0beab0884e07f523, []int{1}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RegisterReq) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

type PathDiscoveryReq struct {
	Uuid                 string      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ProxyPos             *Position   `protobuf:"bytes,2,opt,name=proxyPos,proto3" json:"proxyPos,omitempty"`
	Path                 []*Position `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PathDiscoveryReq) Reset()         { *m = PathDiscoveryReq{} }
func (m *PathDiscoveryReq) String() string { return proto.CompactTextString(m) }
func (*PathDiscoveryReq) ProtoMessage()    {}
func (*PathDiscoveryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0beab0884e07f523, []int{2}
}

func (m *PathDiscoveryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathDiscoveryReq.Unmarshal(m, b)
}
func (m *PathDiscoveryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathDiscoveryReq.Marshal(b, m, deterministic)
}
func (m *PathDiscoveryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathDiscoveryReq.Merge(m, src)
}
func (m *PathDiscoveryReq) XXX_Size() int {
	return xxx_messageInfo_PathDiscoveryReq.Size(m)
}
func (m *PathDiscoveryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PathDiscoveryReq.DiscardUnknown(m)
}

var xxx_messageInfo_PathDiscoveryReq proto.InternalMessageInfo

func (m *PathDiscoveryReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PathDiscoveryReq) GetProxyPos() *Position {
	if m != nil {
		return m.ProxyPos
	}
	return nil
}

func (m *PathDiscoveryReq) GetPath() []*Position {
	if m != nil {
		return m.Path
	}
	return nil
}

type MessageHeader struct {
	Uuid                 string    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mtype                string    `protobuf:"bytes,2,opt,name=mtype,proto3" json:"mtype,omitempty"`
	Sync                 bool      `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	Src                  *Position `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  *Position `protobuf:"bytes,5,opt,name=dst,proto3" json:"dst,omitempty"`
	CreateTime           int64     `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_0beab0884e07f523, []int{3}
}

func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (m *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(m, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MessageHeader) GetMtype() string {
	if m != nil {
		return m.Mtype
	}
	return ""
}

func (m *MessageHeader) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

func (m *MessageHeader) GetSrc() *Position {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *MessageHeader) GetDst() *Position {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *MessageHeader) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type Message struct {
	Header               *MessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 string         `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_0beab0884e07f523, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeader() *MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Ack struct {
	Uuid                 string    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code                 uint32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Src                  *Position `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_0beab0884e07f523, []int{5}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Ack) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Ack) GetSrc() *Position {
	if m != nil {
		return m.Src
	}
	return nil
}

func init() {
	proto.RegisterType((*Position)(nil), "Position")
	proto.RegisterType((*RegisterReq)(nil), "RegisterReq")
	proto.RegisterType((*PathDiscoveryReq)(nil), "PathDiscoveryReq")
	proto.RegisterType((*MessageHeader)(nil), "MessageHeader")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Ack)(nil), "Ack")
}

func init() {
	proto.RegisterFile("proto/tasknet.proto", fileDescriptor_0beab0884e07f523)
}

var fileDescriptor_0beab0884e07f523 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x25, 0x26, 0x3b, 0x93, 0xa9, 0x38, 0x7e, 0xb4, 0x7b, 0x08, 0x2b, 0x4a, 0x0c, 0x28, 0xc1,
	0x43, 0x94, 0xf1, 0x28, 0x08, 0xca, 0x0a, 0x2a, 0x28, 0x43, 0xef, 0x9c, 0x3c, 0xd9, 0x9b, 0x94,
	0x3b, 0x21, 0x3b, 0xe9, 0xd8, 0xd5, 0xbb, 0x9a, 0xbf, 0xe3, 0xc5, 0xbf, 0x29, 0x5d, 0x9b, 0x2c,
	0x19, 0x37, 0x9e, 0xba, 0xba, 0xde, 0xa3, 0xea, 0xbd, 0xaa, 0x82, 0x07, 0xad, 0xd1, 0x56, 0xbf,
	0xb0, 0x8a, 0xea, 0x06, 0x6d, 0xce, 0xbf, 0xf4, 0x1b, 0x84, 0x6b, 0x4d, 0x95, 0xad, 0x74, 0x23,
	0x04, 0x04, 0x46, 0x9f, 0x63, 0xec, 0x25, 0x5e, 0xb6, 0x90, 0x1c, 0x8b, 0xc7, 0x00, 0x84, 0xe6,
	0x12, 0x8d, 0x54, 0x4d, 0x1d, 0xdf, 0x62, 0x64, 0x94, 0x11, 0x09, 0x44, 0xad, 0xd1, 0x05, 0x12,
	0x31, 0xc1, 0x67, 0xc2, 0x38, 0x95, 0xbe, 0x81, 0x48, 0xe2, 0x59, 0x45, 0x16, 0x8d, 0xc4, 0x1f,
	0xae, 0xc9, 0xc5, 0x45, 0x55, 0x0e, 0x4d, 0x5c, 0x2c, 0x1e, 0x82, 0xdf, 0x6a, 0xe2, 0xea, 0xd1,
	0x6a, 0x91, 0x0f, 0x82, 0xa4, 0xcb, 0xa6, 0xe7, 0x70, 0x6f, 0xad, 0xec, 0xf6, 0xb8, 0xa2, 0x42,
	0x5f, 0xa2, 0xe9, 0xfe, 0x57, 0xe4, 0x29, 0x84, 0xad, 0xd1, 0xbf, 0xba, 0xf5, 0x54, 0xa5, 0x6b,
	0x48, 0x3c, 0x82, 0xa0, 0x55, 0x76, 0x1b, 0xfb, 0x89, 0xbf, 0x4f, 0xe1, 0x74, 0xfa, 0xc7, 0x83,
	0xe5, 0x67, 0x24, 0x52, 0x67, 0xf8, 0x01, 0x55, 0x89, 0x66, 0xb2, 0xd7, 0x21, 0x1c, 0xec, 0x6c,
	0xd7, 0x62, 0x3f, 0x90, 0xab, 0x8f, 0x63, 0x52, 0xd7, 0x14, 0x3c, 0x84, 0x50, 0x72, 0xec, 0xac,
	0x91, 0x29, 0xe2, 0xe0, 0x86, 0x35, 0x32, 0x0c, 0x96, 0x64, 0xe3, 0x83, 0x1b, 0x60, 0x49, 0xd6,
	0x4d, 0xbe, 0x30, 0xa8, 0x2c, 0x6e, 0xaa, 0x1d, 0xc6, 0xb3, 0xc4, 0xcb, 0x7c, 0x39, 0xca, 0xa4,
	0xef, 0x61, 0xde, 0x0b, 0x15, 0xcf, 0x60, 0xb6, 0x65, 0xb1, 0x2c, 0x32, 0x5a, 0xdd, 0xc9, 0xf7,
	0x2c, 0xc8, 0x1e, 0x75, 0x02, 0x4f, 0x75, 0xd9, 0xf5, 0xaa, 0x39, 0x4e, 0x3f, 0x81, 0xff, 0xb6,
	0xa8, 0x27, 0x5d, 0x0a, 0x08, 0x0a, 0x5d, 0x5e, 0x99, 0x5c, 0x4a, 0x8e, 0x07, 0x3f, 0xfe, 0x94,
	0x9f, 0xd5, 0x6f, 0x0f, 0xe6, 0x1b, 0x45, 0xf5, 0x17, 0x74, 0xf2, 0xc3, 0x61, 0xed, 0xe2, 0x76,
	0x3e, 0xba, 0x80, 0xa3, 0x20, 0x77, 0x0d, 0x33, 0x58, 0xee, 0xad, 0x55, 0xdc, 0xcf, 0xff, 0x5d,
	0x73, 0xcf, 0x7c, 0x02, 0x77, 0x37, 0x46, 0x35, 0xf4, 0x1d, 0xcd, 0x60, 0x38, 0x1c, 0x0c, 0xf6,
	0x94, 0xe7, 0x70, 0xf8, 0xb1, 0xa9, 0xec, 0x09, 0xdf, 0xe5, 0xb1, 0xfe, 0xd9, 0x9c, 0x58, 0x83,
	0x6a, 0x27, 0x18, 0x3d, 0xba, 0x66, 0x67, 0xde, 0x4b, 0xef, 0xdd, 0xe2, 0xeb, 0x3c, 0x7f, 0xcd,
	0xc7, 0x7f, 0x3a, 0xe3, 0xe7, 0xd5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xca, 0xb8, 0x72,
	0x1a, 0x03, 0x00, 0x00,
}
